! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The Reaction Rates File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : cacm3_Rates.f90
! Time                 : Thu Jan 23 11:51:16 2020
! Working directory    : /home/dandanwe/boxmox/tmp_cacm3_4449_BOXMOX
! Equation file        : cacm3.kpp
! Output root filename : cacm3
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE cacm3_Rates

  USE cacm3_Parameters
  USE cacm3_Precision, ONLY:dp
!!  USE cacm3_Global
!  USE cacm3_Util
  IMPLICIT NONE

CONTAINS



! Begin Rate Law Functions from KPP_HOME/util/UserRateLaws

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  User-defined Rate Law functions
!  Note: the default argument type for rate laws, as read from the equations file, is single precision
!        but all the internal calculations are performed in double precision
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!~~~>  Arrhenius
!   REAL(kind=dp) FUNCTION ARR( A0,B0,C0 )
!      REAL A0,B0,C0
!      ARR =  DBLE(A0) * EXP(-DBLE(B0)/TEMP) * (TEMP/300.0_dp)**DBLE(C0)
!   END FUNCTION ARR

! Arrhenius (added by psaide 15-07-2009)
    REAL(kind=dp) FUNCTION ARR( A0,B0,C0, TEMP )
      REAL(kind=dp) :: TEMP
      REAL(kind=dp) A0,B0,C0
      ARR =  A0 * EXP( -B0 /TEMP ) * (TEMP/300._dp)**C0
    END FUNCTION ARR

!~~~> Simplified Arrhenius, with two arguments
!~~~> Note: The argument B0 has a changed sign when compared to ARR
!   REAL(kind=dp) FUNCTION ARR2( A0,B0 )
!      REAL A0,B0
!      ARR2 =  DBLE(A0) * EXP( DBLE(B0)/TEMP )
!   END FUNCTION ARR2
! CK 20140313 WRF-chem uses different kind of Arrhenius function
!             with TEMP as argument...
   REAL(kind=dp) FUNCTION ARR2( A0,B0, TEMP )
      REAL(kind=dp) :: TEMP
      REAL(kind=dp) A0,B0
      ARR2 = A0 * EXP( -B0 /TEMP )
   END FUNCTION ARR2
! CK 20140313 end

!   REAL(kind=dp) FUNCTION EP2(A0,C0,A2,C2,A3,C3)
!      REAL A0,C0,A2,C2,A3,C3
!      REAL(kind=dp) K0,K2,K3
!      K0 = DBLE(A0) * EXP(-DBLE(C0)/TEMP)
!      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
!      K3 = DBLE(A3) * EXP(-DBLE(C3)/TEMP)
!      K3 = K3*CFACTOR*1.0E6_dp
!      EP2 = K0 + K3/(1.0_dp+K3/K2 )
!   END FUNCTION EP2

!   REAL(kind=dp) FUNCTION EP3(A1,C1,A2,C2)
!      REAL A1, C1, A2, C2
!      REAL(kind=dp) K1, K2
!      K1 = DBLE(A1) * EXP(-DBLE(C1)/TEMP)
!      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
!      EP3 = K1 + K2*(1.0E6_dp*CFACTOR)
!   END FUNCTION EP3

! EP2 (added by psaide 22-07-2009)
   REAL(kind=dp) FUNCTION EP2( A0,C0,A2,C2,A3,C3,TEMP,cair)
      REAL(kind=dp) :: TEMP
      REAL(kind=dp) :: cair
      REAL(kind=dp) A0,C0,A2,C2,A3,C3
      REAL(kind=dp) K0,K2,K3

      K0 = A0 * EXP(-C0 /TEMP)
      K2 = A2 * EXP(-C2 /TEMP)
      K3 = A3 * EXP(-C3 /TEMP)
!      K3 = K3 * 2.45E13_dp * 1.0E6_dp
      K3 = K3 * cair
      EP2 = K0 + K3/(1._dp+K3/K2 )
   END FUNCTION EP2

! EP3 (added by psaide 15-07-2009)
    REAL(kind=dp) FUNCTION EP3(A1,C1,A2,C2,TEMP,cair)
      REAL(kind=dp) :: TEMP
      REAL(kind=dp) :: cair
      REAL(kind=dp) A1, C1, A2, C2
      REAL(kind=dp) K1, K2

      K1 = A1 * EXP(-C1 /TEMP)
      K2 = A2 * EXP(-C2 /TEMP)
!      EP3 = K1 + K2*(1.0E6_dp * 2.45E13_dp)
      EP3 = K1 + K2*cair
    END FUNCTION EP3


!   REAL(kind=dp) FUNCTION FALL ( A0,B0,C0,A1,B1,C1,CF)
!      REAL A0,B0,C0,A1,B1,C1,CF
!      REAL(kind=dp) K0, K1
!      K0 = DBLE(A0) * EXP(-DBLE(B0)/TEMP)* (TEMP/300.0_dp)**DBLE(C0)
!      K1 = DBLE(A1) * EXP(-DBLE(B1)/TEMP)* (TEMP/300.0_dp)**DBLE(C1)
!      K0 = K0*CFACTOR*1.0E6_dp
!      K1 = K0/K1
!      FALL = (K0/(1.0_dp+K1))*   &
!           DBLE(CF)**(1.0_dp/(1.0_dp+(LOG10(K1))**2))
!   END FUNCTION FALL

! FALL (added by psaide 15-07-2009)
    REAL(kind=dp) FUNCTION FALL( A0,B0,C0,A1,B1,C1,CF,TEMP,cair)

      INTRINSIC LOG10

      REAL(kind=dp) :: TEMP
      REAL(kind=dp) :: cair
      REAL(kind=dp) A0,B0,C0,A1,B1,C1,CF
      REAL(kind=dp) K0, K1

      K0 = A0 * EXP(-B0 /TEMP)* (TEMP/300._dp)**C0
      K1 = A1 * EXP(-B1 /TEMP)* (TEMP/300._dp)**C1
!      K0 = K0 * 2.45E13_dp * 1.0E6_dp
      K0 = K0 * cair
      K1 = K0/K1
      FALL = (K0/(1._dp+K1))*CF**(1._dp/(1._dp+(LOG10(K1))**2))

    END FUNCTION FALL

! FALL2 (added by psaide 28-10-2009)
    REAL(KIND=dp) FUNCTION F2( A0,B0,C0,A1,B1,C1,CF,CN,TEMP,cair)

      INTRINSIC LOG10

      REAL(KIND=dp) :: TEMP
      REAL(KIND=dp) :: cair
      REAL(KIND=dp) A0,B0,C0,A1,B1,C1,CF,CN
      REAL(KIND=dp) K0, K1

      K0 = A0 * EXP(-B0 /TEMP)* (TEMP/300._dp)**C0
      K1 = A1 * EXP(-B1 /TEMP)* (TEMP/300._dp)**C1
!      K0 = K0 * 2.45E13_dp * 1.0E6_dp
      K0 = K0 * cair
      K1 = K0/K1
      F2 = (K0/(1._dp+K1))*CF**(1._dp/(1._dp+(LOG10(K1)/CN)**2))

    END FUNCTION F2


  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_3rd(temp,cair,k0_300K,n,kinf_300K,m,fc)

    INTRINSIC LOG10

    REAL(kind=dp), INTENT(IN) :: temp      ! temperature [K]
    REAL(kind=dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL, INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL, INTENT(IN) :: n         ! exponent for low pressure limit
    REAL, INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL, INTENT(IN) :: m         ! exponent for high pressure limit
    REAL, INTENT(IN) :: fc        ! broadening factor (usually fc=0.6)
    REAL(kind=dp) :: zt_help, k0_T, kinf_T, k_ratio

    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    k_3rd   = k0_T/(1._dp+k_ratio)*fc**(1._dp/(1._dp+LOG10(k_ratio)**2))

  END FUNCTION k_3rd

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_arr (k_298,tdep,temp)
    ! Arrhenius function

    REAL,     INTENT(IN) :: k_298 ! k at T = 298.15K
    REAL,     INTENT(IN) :: tdep  ! temperature dependence
    REAL(kind=dp), INTENT(IN) :: temp  ! temperature

    INTRINSIC EXP

    k_arr = k_298 * EXP(tdep*(1._dp/temp-3.3540E-3_dp)) ! 1/298.15=3.3540e-3

  END FUNCTION k_arr

! CK 20140313 in the following some more rate functions needed by
!             WRF-chem packages

!------------------------------------
! Troe reactions (as in Stockwell et al, 1997)

    REAL(kind=dp) FUNCTION TROE(k0_300K,n,kinf_300K,m,temp,cair)

    INTRINSIC LOG10

    REAL(kind=dp), INTENT(IN) :: temp      ! temperature [K]
    REAL(kind=dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL(kind=dp),          INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL(kind=dp),          INTENT(IN) :: n         ! exponent for low pressure limit
    REAL(kind=dp),          INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL(kind=dp),          INTENT(IN) :: m         ! exponent for high pressure limit
    REAL(kind=dp)             :: zt_help, k0_T, kinf_T, k_ratio

    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    TROE   = k0_T/(1._dp+k_ratio)*0.6_dp**(1._dp/(1._dp+LOG10(k_ratio)**2))

   END FUNCTION TROE



!-------------------------------------------
! Troe equilibrium reactions (as in Stockwell et al, 1997)

    REAL(kind=dp) FUNCTION TROEE(A, B, k0_300K,n,kinf_300K,m,temp,cair)

    INTRINSIC LOG10

    REAL(kind=dp), INTENT(IN) :: temp      ! temperature [K]
    REAL(kind=dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL(kind=dp),     INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL(kind=dp),     INTENT(IN) :: n         ! exponent for low pressure limit
    REAL(kind=dp),     INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL(kind=dp),     INTENT(IN) :: m         ! exponent for high pressure limit
    REAL(kind=dp),     INTENT(IN) :: A, B
    REAL(kind=dp)             :: zt_help, k0_T, kinf_T, k_ratio, troe


    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    troe   = k0_T/(1._dp+k_ratio)*0.6_dp**(1._dp/(1._dp+LOG10(k_ratio)**2))

    TROEE = A * EXP( - B / temp) * troe



  END FUNCTION TROEE

!------------------------
! k=T^2 C exp (-D/T) reactions

   REAL(kind=dp) FUNCTION THERMAL_T2(c, d ,temp)
    REAL(kind=dp), INTENT(IN) :: temp      ! temperature [K]
    REAL(kind=dp),     INTENT(IN) :: c, d


     THERMAL_T2= temp**2._dp * c * EXP(- d  / temp)

   END FUNCTION THERMAL_T2

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  End of User-defined Rate Law functions
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! End Rate Law Functions from KPP_HOME/util/UserRateLaws


! Begin INLINED Rate Law Functions
      REAL*8 FUNCTION AR(A0, B0, C0,TEMP)
       
      use cacm3_Parameters
      USE cacm3_Precision, ONLY:dp
!      use cacm3_Global
      
      real A0, B0, C0
      REAL(KIND=dp) TEMP 
      AR = DBLE(A0)*(TEMP**DBLE(B0))*EXP(DBLE(C0)/TEMP)*4.4E+17/TEMP/60.
      
      RETURN
      END
            
      
      REAL*8 FUNCTION AR2(A0, B0, C0, D0, E0, TEMP)
      use cacm3_Parameters
!      use cacm3_Global 

      REAL(KIND=dp) TEMP
      REAL A0, B0, C0, D0, E0
      REAL*8 KO, MO, KINF
      KO = DBLE(A0)*(300./TEMP)**DBLE(B0)
      MO = 7.33853E+21/TEMP
      KINF = DBLE(C0)*(300./TEMP)**DBLE(D0)
      AR2 =  (4.4E+17/TEMP/60.)*KO*MO/(1.0+(KO*MO/KINF))  &
     &        *DBLE(E0)**(1.0 +                           &
     &        (LOG10(KO*MO/KINF))**2)**(-1)
      
      RETURN
      END
      
            
      REAL*8 FUNCTION K10(TEMP)
      use cacm3_Parameters
!      use cacm3_Global     
 
      REAL*8 KO, KINF, MO
      REAL(KIND=dp) TEMP 
      MO = 7.33853E+21/TEMP
      KO = 1.0E-3*(300.0/TEMP)**3.5*EXP(-11001.5/TEMP)
      KINF = 9.7E+14*(TEMP/300.0)**0.1*EXP(-11082.0/TEMP)
      K10  = DBLE(60.0*KO*MO/(1.0+(KO*MO/KINF))              &
     &            *0.45**(1.0+(LOG10(KO*MO/KINF))**2)**(-1))
         K10 = DBLE(K10/60.)
      
      RETURN
      END
      
      
      REAL*8 FUNCTION K22(TEMP)
      use cacm3_Parameters
!      use cacm3_Global

      real*8 KO, KINF, MO
      REAL(KIND=dp) TEMP 
      MO = 7.33853E+21/TEMP  
         KO = 2.85E-30*(300.0/TEMP)**2.67
         KINF = 3.13E-11
         K22 = 0.937*(4.4E+17/TEMP)*KO*MO/(1.0+(0.937*KO*MO/KINF))     &
     &             *(EXP(-1.*TEMP/363.0))**(1.0+                       &
     &              ((LOG10(0.937*KO*MO/KINF)-0.12)/                   &
     &              (0.85-0.67*LOG10(EXP(-1.*TEMP/363.0))))**2)**(-1)
      
         K22 = DBLE(K22/60.)
      RETURN
      END

            
      REAL*8 FUNCTION K23(TEMP)
      use cacm3_Parameters
!      use cacm3_Global

      REAL*8 K1, K2, K3, MO
      REAL(KIND=dp) TEMP 
      MO = 7.33853E+21/TEMP
         K1 = 7.2E-15*EXP(785.1/TEMP)
         K2 = 4.1E-16*EXP(1439.4/TEMP)
         K3 = 1.9E-33*EXP(724.7/TEMP)
         K23 = 4.4E+17/TEMP/60.*(K1 + K3*MO*(1+(K3*MO/K2)))
      
      RETURN
      END
            
      
      REAL*8 FUNCTION K24(TEMP)
      use cacm3_Parameters
!      use cacm3_Global       

      REAL*8 K1, K2, MO
      REAL(KIND=dp) TEMP 
      MO = 7.33853E+21/TEMP    
         K1 = 1.3E-13
         K2 = 3.19E-33
         K24 = 4.4E+17/TEMP/60.*(K1 + K2*MO)
      
      RETURN
      END
            
      
      REAL*8 FUNCTION K28(TEMP)
      use cacm3_Parameters
!      use cacm3_Global

      REAL*8 KO, KINF, MO
      REAL(KIND=dp) TEMP 
      MO = 7.33853E+21/TEMP
         
         KO = 4.1E-5*EXP(-10649.2/TEMP)
         KINF = 5.7E+15*EXP(-11172.6/TEMP)
         K28 = 60.0*KO*MO/60./(1.0+(KO*MO/KINF))          &
     &          *0.5**(1.0+(LOG10(KO*MO/KINF))**2)**(-1)

      RETURN
      END
      
      
      REAL*8 FUNCTION K31()
      use cacm3_Parameters
!      use cacm3_Global

      REAL*8 K1, K2, MO
      REAL(KIND=dp) TEMP 
         MO = 7.33853E+21/TEMP
         K1 = 2.2E-13*EXP(598.9/TEMP)
         K2 = 1.85E-33*EXP(981.4/TEMP)
         K31 = 4.4E+17/TEMP/60.*(K1 + K2*MO)
 
      RETURN
      END
      

      REAL*8 FUNCTION K32()
      use cacm3_Parameters
!      use cacm3_Global

      REAL*8 K1, K2, MO
      REAL(KIND=dp) TEMP 
        MO = 7.33853E+21/TEMP
        K1 = 3.08E-34*EXP(2798.2/TEMP)
        K2 = 2.59E-54*EXP(3180.7/TEMP)
        K32  = 3.23E+33/TEMP/60./TEMP*(K1 + K2*MO)
      RETURN
      END

      REAL*8 FUNCTION K1302(II,TEMP)
     
      use cacm3_Parameters
      include 'user_Parameters.h'
!      use cacm3_Global

      REAL*8 CF_NC, CF_C, Y298, MO, HF1, CF1, CF2
      INTEGER II
      REAL(KIND=dp) TEMP 

      CF_NC = 3.0
      CF_C = 0.4
      Y298 = CF_A*EXP(CF_B*CF_NC)
      MO = 7.33853E+21/TEMP

       HF1 = CF_C*(Y298*MO)/(1.0+(Y298*MO/CF_YI298/(TEMP/298.0)      &
     &        **(-1.*CF_MINF)))*CF_F**(1.0+(LOG10(Y298*MO/CF_YI298/  &
     &        (TEMP/298.0)**(-1.*CF_MINF)))**2)**(-1)
       CF1 = HF1/(1.0+HF1)
       CF2 = 1.0 - CF1

      IF ( II .EQ. 1) THEN
      K1302 = DBLE (CF1*2.91E-12*EXP(180.2/TEMP)*4.4E+17/TEMP/60.)
      ELSE
      K1302 = DBLE (CF2*2.91E-12*EXP(180.2/TEMP)*4.4E+17/TEMP/60.) 
      END IF

      RETURN 
      END




      REAL*8 FUNCTION K1401(TEMP)
     
      use cacm3_Parameters 
!      use cacm3_Global
      include 'user_Parameters.h'

      REAL(KIND=dp) TEMP 
         K1401 = DBLE(4.4E+17*TEMP*EXP(E/TEMP)*(4.*A*EXP(B/TEMP)       &
     &             + 2.*CC*EXP(D/TEMP) + 2.*F*EXP(G/TEMP)*EXP(E/TEMP)  &
     &             + CC*EXP(D/TEMP)*EXP(E/TEMP))/60.)
      
      RETURN
      END
      
      
      
      REAL*8 FUNCTION K1402(II,TEMP)
      use cacm3_Parameters
!      use cacm3_Global

      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      REAL*8 CF_NC, CF_C, Y298, MO, HF1, CF1, CF2
      INTEGER II     
 
      CF_NC = 8.0
      CF_C = 1.0
      Y298 = CF_A*EXP(CF_B*CF_NC)
      MO = 7.33853E+21/TEMP
            HF1 = CF_C*(Y298*MO)/(1.0+(Y298*MO/CF_YI298/(TEMP/298.0)   &
     &         **(-1.*CF_MINF)))*CF_F**(1.0+(LOG10(Y298*MO/CF_YI298/   &
     &         (TEMP/298.0)**(-1.*CF_MINF)))**2)**(-1)

      CF1 = HF1/(1.0 + HF1)
      CF2 = 1.0 - CF1
      
      IF (II .EQ. 1) THEN
      K1402 = DBLE(1.25E-12*EXP(180.2/TEMP)*4.4E+17/TEMP/60.*CF1)
      ELSE
      K1402 = DBLE(1.25E-12*EXP(180.2/TEMP)*4.4E+17/TEMP/60.*CF2)
      ENDIF
      
      RETURN
      END
      
      
      
      REAL*8 FUNCTION K1501(TEMP)
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'

      REAL(KIND=dp) TEMP 
      
!      REAL*8 A, B, CC, D, E 
        K1501 = DBLE(4.4E+17*TEMP*EXP(E/TEMP)*(2.*A*EXP(B/TEMP)            &
     &          + 2.*CC*EXP(D/TEMP) + 12.*CC*EXP(D/TEMP)*EXP(E/TEMP))/60.)
      
      RETURN
      END
      
      
      
      REAL*8 FUNCTION K1502(II,TEMP)
      use cacm3_Parameters
!      use cacm3_Global    
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      
      REAL*8 CF_NC, CF_C, Y298, MO, HF1, CF1, CF2
      INTEGER II      

      CF_NC = 16.0
      CF_C = 1.0
      Y298 = CF_A*EXP(CF_B*CF_NC)
      MO = 7.33853E+21/TEMP
            HF1 = CF_C*(Y298*MO)/(1.0+(Y298*MO/CF_YI298/(TEMP/298.0)  &
     &         **(-1.*CF_MINF)))*CF_F**(1.0+(LOG10(Y298*MO/CF_YI298/  &
     &         (TEMP/298.0)**(-1.*CF_MINF)))**2)**(-1)

      CF1 = HF1/(1.0 + HF1)
      CF2 = 1.0 - CF1
      
      IF (II .EQ. 1) THEN
      K1502 = DBLE(3.2E-13*EXP(180.2/TEMP)*4.4E17/TEMP/60.*CF1)
      ELSE
      K1502 = DBLE(3.2E-13*EXP(180.2/TEMP)*4.4E17/TEMP/60.*CF2)
      ENDIF
      
      RETURN
      END
      
     
            
      
      REAL*8 FUNCTION K2301(TEMP)
      use cacm3_Parameters
!      use cacm3_Global     
      include 'user_Parameters.h'

      REAL(KIND=dp) TEMP 
 
      K2301 = DBLE(4.4E+17*TEMP*EXP(E/TEMP)*(L*EXP((-1.*E)/TEMP)/TEMP**2    &
     &             + 2.*CC*EXP(D/TEMP) + F*EXP(G/TEMP)*EXP(E/TEMP)          &
     &             + 2.*A*EXP(B/TEMP) + 2.*CC*EXP(D/TEMP)*EXP(E/TEMP))/60.)
      RETURN
      END
      
      
      
      REAL*8 FUNCTION K2302(TEMP)
     
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      
      REAL*8 K54, K55, K74
 
      K54 = 2.58E+06/TEMP*EXP(500.3/TEMP)
      K55 = 4.4E+04/TEMP*EXP(-800.2/TEMP)
      K74 = 4.4E+17*TEMP*EXP(E/TEMP)*(L*EXP((-1.*E)/TEMP)/TEMP**2      &
     &             + 2.*CC*EXP(D/TEMP) + F*EXP(G/TEMP)*EXP(E/TEMP)     &
     &             + 2.*A*EXP(B/TEMP) + 2.*CC*EXP(D/TEMP)*EXP(E/TEMP))
      K2302 = DBLE(K74*K55/K54/60.) 
     
      RETURN
      END
      
      
      
      
      REAL*8 FUNCTION K2303(TEMP)
     
      use cacm3_Parameters
      include 'user_Parameters.h'
!      use cacm3_Global
      REAL(KIND=dp) TEMP 
      
      REAL*8 K54, K56, K74
      
      K54 = 2.58E+06/TEMP*EXP(500.3/TEMP)
      K56 = 4.4/TEMP
      K74 = 4.4E+17*TEMP*EXP(E/TEMP)*(L*EXP((-1.*E)/TEMP)/TEMP**2      &
     &             + 2.*CC*EXP(D/TEMP) + F*EXP(G/TEMP)*EXP(E/TEMP)     & 
     &             + 2.*A*EXP(B/TEMP) + 2.*CC*EXP(D/TEMP)*EXP(E/TEMP))
      K2303 = DBLE(K74*K56/K54/60.) 
     
      RETURN
      END
      
      
      
      
      REAL*8 FUNCTION K2304(TEMP)
     
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'

      REAL(KIND=dp) TEMP 
      
      REAL*8 K54, K57, K74
      
      K54 = 2.58E+06/TEMP*EXP(500.3/TEMP)
      K57 = 2.05E+06/TEMP
      K74 = 4.4E+17*TEMP*EXP(E/TEMP)*(L*EXP((-1.*E)/TEMP)/TEMP**2      &
     &             + 2.*CC*EXP(D/TEMP) + F*EXP(G/TEMP)*EXP(E/TEMP)     & 
     &             + 2.*A*EXP(B/TEMP) + 2.*CC*EXP(D/TEMP)*EXP(E/TEMP))
      K2304 = DBLE(K74*K57/K54/60.) 
     
      RETURN
      END
          
      
      
      
      REAL*8 FUNCTION K2308(TEMP)
     
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      
         K2308 = DBLE(4.4E+17*TEMP*EXP(E/TEMP)*(2.*A*EXP(B/TEMP)    &
     &             + P/TEMP**2 + CC*EXP(D/TEMP)*EXP(K/TEMP)         &
     &             + F*EXP(G/TEMP)*EXP(E/TEMP) + 2.*CC*EXP(D/TEMP)  &
     &             *EXP(E/TEMP) + CC*EXP(D/TEMP))/60.)
      RETURN
      END
      
      
      
      REAL*8 FUNCTION K2309(TEMP)
     
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'

      REAL(KIND=dp) TEMP 
      REAL*8 K60, K61, K300
      
      K60 = 3.039E+06/TEMP*EXP(250/TEMP)
      K61 = 1.32E+05/TEMP*EXP(-1427.0/TEMP)
      K300 = 4.4E+17*TEMP*EXP(E/TEMP)*(2.*A*EXP(B/TEMP)            &
     &             + P/TEMP**2 + CC*EXP(D/TEMP)*EXP(K/TEMP)        &
     &             + F*EXP(G/TEMP)*EXP(E/TEMP) + 2.*CC*EXP(D/TEMP) &
     &             *EXP(E/TEMP) + CC*EXP(D/TEMP))
      K2309 = DBLE(K61*K300/K60/60.)
      
      RETURN
      END
      
      
         
      REAL*8 FUNCTION KPAN(TEMP)
     
      use cacm3_Parameters
!      use cacm3_Global    

      REAL(KIND=dp) TEMP 
      REAL*8 KO, KINF, K1, MO
         KO = 9.7E-29*(300.0/TEMP)**5.6
         KINF = 9.3E-12*(300.0/TEMP)**1.5
         MO = 7.33853E+21/TEMP
         K1 = (4.4E+17/TEMP)*KO*MO/(1.0+(KO*MO/KINF))       &
     &            *0.6**(1.0+(LOG10(KO*MO/KINF))**2)**(-1)
     
      KPAN = DBLE(60.0*1.16E+28*TEMP*EXP(-13954.0/TEMP)     &
     &        *K1/4.4E+17/60.)
     
      RETURN
      END
      
      
      
      REAL*8 FUNCTION K4201(II,TEMP)
      
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      
      REAL*8 CF1, CF2
      INTEGER II
      
      CF1 = (CC*EXP(D/TEMP)*EXP(J/TEMP) + H*EXP(I/TEMP)*EXP(E/TEMP))  &
     &       /(A*EXP(B/TEMP)*EXP(E/TEMP) +                            &
     &       CC*EXP(D/TEMP)*EXP(J/TEMP) + H*EXP(I/TEMP)*EXP(E/TEMP))
      CF2 = 1.0 - CF1
      
      IF ( II .EQ. 1) THEN
      K4201 = DBLE(CF1*2.72*TEMP*EXP(532.0/TEMP)/60.)
      ELSE
      K4201 = DBLE(CF2*2.72*TEMP*EXP(532.0/TEMP)/60.)
      ENDIF
      
      RETURN
      END
           
     
      
      REAL*8 FUNCTION K4301(TEMP)
     
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
           
       K4301 = DBLE(4.4E+17*TEMP*EXP(E/TEMP)*(2.*A*EXP(B/TEMP)            &
     &             + F*EXP(G/TEMP)*EXP(J/TEMP) + H*EXP(I/TEMP)            &
     &             + 2.*CC*EXP(D/TEMP)*EXP(E/TEMP) + CC*EXP(D/TEMP))/60.)
     
      RETURN
      END
     
     
     
      REAL*8 FUNCTION K5201(TEMP)
      use cacm3_Parameters 
      include 'user_Parameters.h'
!      use cacm3_Global     
      REAL(KIND=dp) TEMP 
   
         K5201 = DBLE(4.4E+17*TEMP*EXP(E/TEMP)*(A*EXP(B/TEMP)*     &
     &             EXP((-1.*E)/TEMP)*EXP(K/TEMP) + CC*EXP(D/TEMP)  &
     &             *EXP(K/TEMP) + 2.*CC*EXP(D/TEMP)*EXP(E/TEMP)    &
     &             + CC*EXP(D/TEMP) + A*EXP(B/TEMP))/60.)
      
      RETURN
      END

      REAL*8 FUNCTION TUN( A0,B0,C0,TEMP)
      REAL(KIND=dp) TEMP 
      REAL A0,B0,C0
      REAL*8 Molc2ppm
      Parameter(Molc2ppm = 2.46E13)    
      TUN =  DBLE(A0) * EXP(-DBLE(B0)/TEMP) * EXP(DBLE(C0)/TEMP**3)*Molc2ppm 
      END FUNCTION TUN        

      real*8 FUNCTION ISO1( A0,B0,C0,D0,E0,F0,G0,TEMP ) 
      REAL(KIND=dp) TEMP 
      REAL A0,B0,C0,D0,E0,F0,G0 
      REAL(kind=dp) K0, K1, K2 
      REAL*8 Molc2ppm
      Parameter(Molc2ppm = 2.46E13)    
      K0 = DBLE(D0)*EXP(DBLE(E0)/TEMP)*EXP(1.E8/TEMP**3) 
      K1 = DBLE(F0)*EXP(DBLE(G0)/TEMP) 
      K2 = DBLE(C0)*K0/(K0+K1) 
      ISO1 =  DBLE(A0) * EXP(DBLE(B0)/TEMP) * (1.-K2)*Molc2ppm 
      END FUNCTION ISO1        
 
      real*8 FUNCTION ISO2( A0,B0,C0,D0,E0,F0,G0,TEMP ) 
      REAL A0,B0,C0,D0,E0,F0,G0 
      REAL(KIND=dp) TEMP 
      REAL(kind=dp) K0, K1, K2 
      REAL*8 Molc2ppm
      Parameter(Molc2ppm = 2.46E13)   
      K0 = DBLE(D0)*EXP(DBLE(E0)/TEMP)*EXP(1.E8/TEMP**3) 
      K1 = DBLE(F0)*EXP(DBLE(G0)/TEMP) 
      K2 = DBLE(C0)*K0/(K0+K1) 
      ISO2 =  DBLE(A0) * EXP(DBLE(B0)/TEMP) * K2 * Molc2ppm 
      END FUNCTION ISO2        
 
      real*8 FUNCTION EPO(A1,E1,M1,TEMP)  
      REAL(KIND=dp) TEMP 
      REAL A1, E1, M1 
      REAL(kind=dp) K1       
      REAL(kind=dp), PARAMETER :: Molc2ppm=2.46E+13 
      REAL(kind=dp), PARAMETER :: CFACTOR=2.5E+19 
      K1 = 1.0_dp/(DBLE(M1) * CFACTOR + 1.0_dp) 
      EPO = DBLE(A1) * EXP(DBLE(E1)/TEMP) *  K1 * Molc2ppm 
      END FUNCTION EPO 
 
      real*8 FUNCTION KCO(A1,M1,TEMP)  
      REAL(KIND=dp) TEMP 
      REAL A1, M1 
      REAL*8 Molc2ppm
      Parameter(Molc2ppm = 2.46E13)    
      REAL(kind=dp), PARAMETER :: CFACTOR=2.5E+19 
      KCO = DBLE(A1) * (1.0_dp + (CFACTOR / DBLE(M1))) * Molc2ppm 
      END FUNCTION KCO 
 
      real*8 FUNCTION NIT ( A0,B0,C0,n,X0,Y0,TEMP) 
      REAL(KIND=dp) TEMP 
      REAL A0,B0,C0,n,X0,Y0 
      REAL(kind=dp) K0, K1, K2, K3, K4      
      REAL*8 Molc2ppm
      Parameter(Molc2ppm = 2.46E13)    
      REAL(kind=dp), PARAMETER :: CFACTOR=2.5E+19 
      K0 = 2.0E-22_dp * EXP(DBLE(n)) 
      K1 = 4.3E-1_dp*(TEMP/298.0_dp)**(-8) 
      K0 = K0*CFACTOR 
      K1 = K0/K1 
      K2 = (K0/(1.0_dp+K1))*   & 
           4.1E-1_dp**(1.0_dp/(1.0_dp+(LOG10(K1))**2)) 
      K3 = K2/(K2+DBLE(C0)) 
      K4 = DBLE(A0)*(DBLE(X0)-TEMP*DBLE(Y0)) 
      NIT = K4 * EXP(DBLE(B0)/TEMP) * K3 * Molc2ppm 
      END FUNCTION NIT 
 
      real*8 FUNCTION ALK ( A0,B0,C0,n,X0,Y0,TEMP) 
      REAL(KIND=dp) TEMP 
      REAL A0,B0,C0,n,X0,Y0 
      REAL(kind=dp) K0, K1, K2, K3, K4   
      REAL*8 Molc2ppm
      Parameter(Molc2ppm = 2.46E13)    
      REAL(kind=dp), PARAMETER :: CFACTOR=2.5E+19 
      K0 = 2.0E-22_dp * EXP(DBLE(n)) 
      K1 = 4.3E-1_dp*(TEMP/298.0_dp)**(-8) 
      K0 = K0*CFACTOR 
      K1 = K0/K1 
      K2 = (K0/(1.0_dp+K1))*   & 
           4.1E-1_dp**(1.0_dp/(1.0_dp+(LOG10(K1))**2)) 
      K3 = DBLE(C0)/(K2+DBLE(C0)) 
      K4 = DBLE(A0)*(DBLE(X0)-TEMP*DBLE(Y0)) 
      ALK = K4 * EXP(DBLE(B0)/TEMP) * K3 * Molc2ppm 
      END FUNCTION ALK 

      REAL*8 FUNCTION K7107(TEMP)
       
      use cacm3_Parameters
!      use cacm3_Global
      REAL(KIND=dp) TEMP 
      
      K7107 = DBLE(EXP(101.2976-11.4*LOG(TEMP)-9460./TEMP)/60.*1.2)
     
      RETURN
      END
! POW reaction rates end here

! cacm reaction rates continue...

      REAL*8 FUNCTION K7104(II,TEMP)
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      REAL*8 CF_NC,CF_C, Y298, MO, HF1, CF1, CF2
      INTEGER II

      CF_NC = 9.0
      CF_C = 0.40
      Y298 = CF_A*EXP(CF_NC*CF_B)
      MO = 7.33853E+21/TEMP 
      HF1 =   (CF_C*(Y298*MO)/(1.0+(Y298*MO/CF_YI298/(TEMP/298.0)     &
     &         **(-1.*CF_MINF)))*CF_F**(1.0+(LOG10(Y298*MO/CF_YI298/  &
     &         (TEMP/298.0)**(-1.*CF_MINF)))**2)**(-1))
      
      CF1 = HF1/(1.0 + HF1)
      CF2 = 1.0 - CF1
 
      IF (II .EQ. 1) THEN
      K7104 = DBLE(1.05E-12*EXP(180.2/TEMP)*4.4E+17/TEMP/60.*CF1)
      ELSE
      K7104 = DBLE(1.05E-12*EXP(180.2/TEMP)*4.4E+17/TEMP/60.*CF2)
      ENDIF

      RETURN
      END



      REAL*8 FUNCTION K7114(TEMP)
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      
      K7114 = DBLE(4.4E+17/TEMP*(A*TEMP**2*EXP(B/TEMP)*EXP(K/TEMP)   &
     &             + V + 2.0*A*TEMP**2*EXP(B/TEMP) + W + P)/60.)
      RETURN
      END 


      
      REAL*8 FUNCTION K7115(TEMP)
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 

      K7115 = DBLE(4.4E+17/TEMP*(P + Q + S + A*TEMP*TEMP*  &
     &             EXP(B/TEMP))/60.)

      RETURN
      END

      
      
      REAL*8 FUNCTION K7201(TEMP)
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 

       K7201 = DBLE(4.4E+17*TEMP*EXP(E/TEMP)*(1.26E-11*EXP((-1.*E)/TEMP)  &
     &             /TEMP**2 + A*EXP(B/TEMP)*EXP((-1.*E)/TEMP)             &
     &             + 2.*CC*EXP(D/TEMP) + A*EXP(B/TEMP))/60.)

      RETURN
      END

      
      
      REAL*8 FUNCTION K7203(TEMP)
       
      use cacm3_Parameters
!      use cacm3_Global
      REAL(KIND=dp) TEMP 
      
      K7203 = DBLE(EXP(101.2976-11.4*LOG(TEMP)-9460./TEMP)/60.*1.1)
     
      RETURN
      END
      

      
      REAL*8 FUNCTION K7302(TEMP)
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 

       K7302 = DBLE(4.4E+17*TEMP*(2.26E-10/TEMP**2 +       &
     &             2.*A*EXP(B/TEMP) + H*EXP(I/TEMP))/60.)
      RETURN
      END

      
      
      REAL*8 FUNCTION K7306(II,TEMP)
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      REAL*8 CF_NC,CF_C, Y298, MO, HF1, CF1, CF2
      INTEGER II

      CF_NC = 8.0
      CF_C = 0.40
      Y298 = CF_A*EXP(CF_NC*CF_B)
      MO = 7.33853E+21/TEMP 
      HF1 = 0.4*(CF_C*(Y298*MO)/(1.0+(Y298*MO/CF_YI298/(TEMP/298.0)   &
     &         **(-1.*CF_MINF)))*CF_F**(1.0+(LOG10(Y298*MO/CF_YI298/  &
     &         (TEMP/298.0)**(-1.*CF_MINF)))**2)**(-1))+1.0-0.4
      
      CF1 = HF1/(1.0 + HF1)
      CF2 = 1.0 - CF1
 
      IF (II .EQ. 1) THEN
      K7306 = DBLE(1.25E-12*EXP(180.2/TEMP)*4.4E+17/TEMP/60.*CF1)
      ELSE
      K7306 = DBLE(1.25E-12*EXP(180.2/TEMP)*4.4E+17/TEMP/60.*CF2)
      ENDIF

      RETURN
      END

      

      REAL*8 FUNCTION K7319(TEMP)
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 

      K7319 = DBLE(4.4E+17*TEMP*(2.0*A*EXP(B/TEMP) + V/TEMP/TEMP +     &
     &             Q/TEMP/TEMP + 2.0*P/TEMP/TEMP + H*EXP(I/TEMP))/60.)
      RETURN
      END



      REAL*8 FUNCTION K7320(TEMP)
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      K7320 = DBLE(4.4E+17/TEMP*(2.0*A*TEMP**2*EXP(B/TEMP) +     &
     &             V + P + Q + H*TEMP**2*EXP(I/TEMP) + S)/60.)

      RETURN
      END
  
      
      
      REAL*8 FUNCTION K7402(II,TEMP)
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      
      REAL KTEMP, CF1, CF2, CF3, CF4
      INTEGER II
      
      KTEMP = 1.29E-11*4.4E+17/TEMP/60.
      CF1 = 0.16
      CF2 = 2.22E-11/(2.22E-11 + 7.66E-12 + (4.49E-18 *  &
     &         TEMP *TEMP * EXP(-320.0/TEMP)))
      CF4 = 4.49E-18*TEMP*TEMP*EXP(-320.0/TEMP)          &
     &         /(2.22E-11 + 7.66E-12 + (4.49E-18 *       &
     &         TEMP *TEMP * EXP(-320.0/TEMP)))
      CF3 = 0.84 - CF2 - CF4
      
      IF (II .EQ. 1) THEN
      K7402 = DBLE(KTEMP*CF1)
      ELSE IF (II .EQ. 2) THEN
      K7402 = DBLE(KTEMP*CF2)
      ELSE IF (II .EQ. 3) THEN
      K7402 = DBLE(KTEMP*CF3)
      ELSE 
      K7402 = DBLE(KTEMP*CF4)
      END IF
            
      RETURN
      END



      REAL*8 FUNCTION K7405(II,TEMP)
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      REAL*8 CF_NC,CF_C, Y298, MO, HF1, CF1, CF2
      INTEGER II

      CF_NC = 8.0
      CF_C = 0.40
      Y298 = CF_A*EXP(CF_NC*CF_B)
      MO = 7.33853E+21/TEMP 
      HF1 = CF_C*(Y298*MO)/(1.0+(Y298*MO/CF_YI298/(TEMP/298.0)         &
     &         **(-1.*CF_MINF)))*CF_F**(1.0+(LOG10(Y298*MO/CF_YI298/   &
     &         (TEMP/298.0)**(-1.*CF_MINF)))**2)**(-1)
      CF1 = HF1/(1.0 + HF1)
      CF2 = 1.0 - CF1
 
      IF (II .EQ. 1) THEN
      K7405 = DBLE(1.25E-12*EXP(180.2/TEMP)*4.4E+17/TEMP/60.*CF1)
      ELSE
      K7405 = DBLE(1.25E-12*EXP(180.2/TEMP)*4.4E+17/TEMP/60.*CF2)
      ENDIF

      RETURN
      END



      REAL*8 FUNCTION K7417(TEMP)
      
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      
      K7417 = DBLE(4.4E+17/TEMP*(A*TEMP**2*EXP(B/TEMP)     &
     &             + 2.0*Q + 3.0*P)/60.)
     
      RETURN
      END
      
      
      
      
      REAL*8 FUNCTION K7419(TEMP)
      
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      
      K7419 = DBLE(4.4E+17/TEMP*(A*TEMP**2*EXP(B/TEMP)     &
     &             + 2.0*Q + 2.0*P + S)/60.)
     
      RETURN
      END
      
      
      
      REAL*8 FUNCTION K7420(TEMP)
      
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      
      K7420 = DBLE(4.4E+17/TEMP*(A*TEMP**2*EXP(B/TEMP)     &
     &             + 2.0*Q + 2.0*S + P)/60.)
     
      RETURN
      END
      
      
      
      REAL*8 FUNCTION K7504(II,TEMP)
      
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      
      REAL*8 CF_NC,CF_C, Y298, MO, HF1, CF1, CF2
      INTEGER II

      CF_NC = 8.0
      CF_C = 0.40
      Y298 = CF_A*EXP(CF_NC*CF_B)
      MO = 7.33853E+21/TEMP 
      HF1 =   (CF_C*(Y298*MO)/(1.0+(Y298*MO/CF_YI298/(TEMP/298.0)     &
     &         **(-1.*CF_MINF)))*CF_F**(1.0+(LOG10(Y298*MO/CF_YI298/  &
     &         (TEMP/298.0)**(-1.*CF_MINF)))**2)**(-1))
      
      CF1 = HF1/(1.0 + HF1)
      CF2 = 1.0 - CF1
 
      IF (II .EQ. 1) THEN
      K7504 = DBLE(1.25E-12*EXP(180.2/TEMP)*4.4E+17/TEMP/60.*CF1)
      ELSE
      K7504 = DBLE(1.25E-12*EXP(180.2/TEMP)*4.4E+17/TEMP/60.*CF2)
      ENDIF
         
      
      RETURN
      END
      
      
      
      
      REAL*8 FUNCTION K7604(II,TEMP)
      
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      
      REAL*8 CF_NC,CF_C, Y298, MO, HF1, CF1, CF2
      INTEGER II

      CF_NC = 12.0
      CF_C = 0.40
      Y298 = CF_A*EXP(CF_NC*CF_B)
      MO = 7.33853E+21/TEMP 
      HF1 =   (CF_C*(Y298*MO)/(1.0+(Y298*MO/CF_YI298/(TEMP/298.0)     &
     &         **(-1.*CF_MINF)))*CF_F**(1.0+(LOG10(Y298*MO/CF_YI298/  &
     &         (TEMP/298.0)**(-1.*CF_MINF)))**2)**(-1))
      
      CF1 = HF1/(1.0 + HF1)
      CF2 = 1.0 - CF1
 
      IF (II .EQ. 1) THEN
      K7604 = DBLE(6.32E-13*EXP(180.2/TEMP)*4.4E+17/TEMP/60.*CF1)
      ELSE
      K7604 = DBLE(6.32E-13*EXP(180.2/TEMP)*4.4E+17/TEMP/60.*CF2)
      ENDIF
         
      
      RETURN
      END
            
      
          
       
      REAL*8 FUNCTION K7614(TEMP)
      
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      
      K7614 = DBLE((5.68E+06/TEMP+4.4E+17/TEMP*(2*A*TEMP**2*EXP(B/TEMP)  &
     &            + V + P))/60.)
      
      RETURN
      END 

      
      
      REAL*8 FUNCTION K7615(TEMP)
      
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      
      K7615 = DBLE((5.68E+06/TEMP + 4.4E+17*TEMP*A*EXP(B/TEMP)  &
     &             *EXP(K/TEMP))/60.)
      
      RETURN
      END 

      
      
      REAL*8 FUNCTION K7616(TEMP)
      
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      K7616 = DBLE((4.64E+05/TEMP &
     &          + 4.4E+17/TEMP*(2.0*A*TEMP**2*EXP(B/TEMP)   &
     &          + V + P))/60.)
      
      RETURN
      END 

      REAL*8 FUNCTION K8111(II,TEMP)

      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      REAL*8 CF_NC,CF_C, Y298, MO, HF1, CF1, CF2
      INTEGER II

      CF_NC = 9.0
      CF_C = 0.40
      Y298 = CF_A*EXP(CF_NC*CF_B)
      MO = 7.33853E+21/TEMP 
      HF1 =  CF_C*(Y298*MO)/(1.0+(Y298*MO/CF_YI298/(TEMP/298.0)       &
     &         **(-1.*CF_MINF)))*CF_F**(1.0+(LOG10(Y298*MO/CF_YI298/  &
     &         (TEMP/298.0)**(-1.*CF_MINF)))**2)**(-1)
      
      CF1 = HF1/(1.0 + HF1)
      CF2 = 1.0 - CF1
 
      IF (II .EQ. 1) THEN
      K8111 = DBLE(1.05E-12*EXP(180.2/TEMP)*4.4E+17/TEMP/60.*CF1)
      ELSE
      K8111 = DBLE(1.05E-12*EXP(180.2/TEMP)*4.4E+17/TEMP/60.*CF2)
      ENDIF

      RETURN
      END




      REAL*8 FUNCTION K8136(II,TEMP)

      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      REAL*8 CF_NC,CF_C, Y298, MO, HF1, CF1, CF2
      INTEGER II

      CF_NC = 8.0
      CF_C = 1.0
      Y298 = CF_A*EXP(CF_NC*CF_B)
      MO = 7.33853E+21/TEMP 
      HF1 =  CF_C*(Y298*MO)/(1.0+(Y298*MO/CF_YI298/(TEMP/298.0)       &
     &         **(-1.*CF_MINF)))*CF_F**(1.0+(LOG10(Y298*MO/CF_YI298/  &
     &         (TEMP/298.0)**(-1.*CF_MINF)))**2)**(-1)
      
      CF1 = HF1/(1.0 + HF1)
      CF2 = 1.0 - CF1
 
      IF (II .EQ. 1) THEN
      K8136 = DBLE(1.05E-12*EXP(180.2/TEMP)*4.4E+17/TEMP/60.*CF1)
      ELSE
      K8136 = DBLE(1.05E-12*EXP(180.2/TEMP)*4.4E+17/TEMP/60.*CF2)
      ENDIF

      RETURN
      END



      REAL*8 FUNCTION K8144(TEMP)

      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 


      K8144=DBLE(4.4E+17*TEMP*(F*EXP(G/TEMP)*EXP(EX4/TEMP)*EXP(E/TEMP)       &
     &         + CC*EXP(D/TEMP)*EXP(K/TEMP)*EXP(E/TEMP)                      &
     &         + F*EXP(G/TEMP)*(EXP(E/TEMP)**3)*EXP(EX3/TEMP)                &
     &         + CC*EXP(D/TEMP)*EXP(E/TEMP)*EXP(E/TEMP)*EXP(EX3/TEMP)        &
     &         + F*EXP(G/TEMP)*(EXP(E/TEMP)**2)*EXP(EX6/TEMP)*EXP(EX3/TEMP)  &
     &         + 2*A*EXP(B/TEMP)*EXP(E/TEMP)                                 &
     &         + S*EXP(E/TEMP)/TEMP/TEMP)/60.)     

      RETURN
      END
      

      REAL*8 FUNCTION K8145(TEMP)

      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 


      K8145=DBLE(4.4E+17*TEMP*(F*EXP(G/TEMP)*EXP(EX4/TEMP)*EXP(E/TEMP)    &
     &         + CC*EXP(D/TEMP)*EXP(K/TEMP)*EXP(E/TEMP)                   &
     &         + F*EXP(G/TEMP)*(EXP(E/TEMP)**3)*EXP(EX3/TEMP)             &
     &         + CC*EXP(D/TEMP)*EXP(E/TEMP)*EXP(E/TEMP)*EXP(EX3/TEMP)     &
     &         + H*EXP(I/TEMP)*EXP(E/TEMP)                                &
     &         + 2*A*EXP(B/TEMP)*EXP(E/TEMP)                              &
     &         + A*EXP(B/TEMP)*EXP(EX2/TEMP))/60.) 

      RETURN
      END

      
      REAL*8 FUNCTION K8146(TEMP)

      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
     
      K8146=DBLE(4.4E+17*TEMP*(F*EXP(G/TEMP)*EXP(EX4/TEMP)*EXP(E/TEMP)       &
     &         + CC*EXP(D/TEMP)*EXP(K/TEMP)*EXP(E/TEMP)                      &
     &         + F*EXP(G/TEMP)*(EXP(E/TEMP)**3)*EXP(EX3/TEMP)                &
     &         + CC*EXP(D/TEMP)*EXP(E/TEMP)*EXP(E/TEMP)*EXP(EX3/TEMP)        &
     &         + F*EXP(G/TEMP)*EXP(EX2/TEMP)*(EXP(E/TEMP)**2)*EXP(EX3/TEMP)  &
     &         + CC*EXP(D/TEMP)*EXP(EX3/TEMP)*EXP(J/TEMP)                    &
     &         + H*EXP(I/TEMP)*EXP(E/TEMP)                                   &
     &         + 2*A*EXP(B/TEMP)*EXP(E/TEMP))/60.) 


      RETURN
      END



      REAL*8 FUNCTION K8372(TEMP)

      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 

      K8372= DBLE(4.4E+17*TEMP*(A*EXP(B/TEMP)*EXP(EX2/TEMP) +        &
     &            CC*EXP(D/TEMP)*EXP(K/TEMP)*EXP(E/TEMP) +           &
     &            CC*EXP(D/TEMP)*EXP(E/TEMP)*EXP(E/TEMP) +           &
     &            F*EXP(G/TEMP)*EXP(E/TEMP)*EXP(E/TEMP)*EXP(K/TEMP)  &
     &            + CC*EXP(D/TEMP)*EXP(E/TEMP)*EXP(K/TEMP) +         &
     &            A*EXP(B/TEMP)*EXP(EX2/TEMP) +                      &
     &            F*EXP(G/TEMP)*EXP(EX4/TEMP)*EXP(E/TEMP))/60.)


      RETURN
      END
      


      REAL*8 FUNCTION K8373(TEMP)

      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 


      K8373= DBLE(4.4E+17*TEMP*(A*EXP(B/TEMP)*EXP(EX2/TEMP) +    &
     &            CC*EXP(D/TEMP)*EXP(K/TEMP)*EXP(E/TEMP) +       &
     &            CC*EXP(D/TEMP)*EXP(EX2/TEMP)*EXP(E/TEMP) +     &
     &            CC*EXP(D/TEMP)*EXP(K/TEMP)*EXP(EX2/TEMP) +     &
     &            F*EXP(G/TEMP)*EXP(EX4/TEMP)*EXP(E/TEMP))/60.)


      RETURN
      END
      


      REAL*8 FUNCTION K8374(TEMP)

      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 

      K8374= DBLE(4.4E+17*TEMP*(A*EXP(B/TEMP)*EXP(EX2/TEMP)           &
     &      + 2*CC*EXP(D/TEMP)*EXP(E/TEMP)*EXP(E/TEMP)*EXP(K/TEMP)    &
     &      + 2*F*EXP(G/TEMP)*EXP(EX4/TEMP)*EXP(E/TEMP)               &
     &      + F*EXP(G/TEMP)*EXP(E/TEMP)*EXP(E/TEMP)*EXP(K/TEMP))/60.)


      RETURN
      END

      
      
      REAL*8 FUNCTION K8375(TEMP)

      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 

      K8375= DBLE((4.4E+17*TEMP*(A*EXP(B/TEMP)*EXP(EX1/TEMP) +         &
     &            CC*EXP(D/TEMP)*EXP(EX1/TEMP)*EXP(E/TEMP) +           &
     &            CC*EXP(D/TEMP)*EXP(E/TEMP)**2 +                      &
     &            F*EXP(G/TEMP)*EXP(E/TEMP)**2 +                       &
     &            CC*EXP(D/TEMP)*EXP(E/TEMP)**2 +                      &
     &            F*EXP(G/TEMP)*EXP(EX1/TEMP)*EXP(J/TEMP)*EXP(E/TEMP)  &
     &            + A*EXP(B/TEMP) +                                    &
     &            H*EXP(I/TEMP)*EXP(E/TEMP) + T/TEMP/TEMP*EXP(E/TEMP)) &
     &            + 4.4E+17/TEMP*EX5)/60.)


      RETURN
      END



      REAL*8 FUNCTION K8376(TEMP)

      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 

      K8376= DBLE((4.4E+17*TEMP*(A*EXP(B/TEMP)                         &
     &          + CC*EXP(D/TEMP)*EXP(E/TEMP)                           &
     &          + CC*EXP(D/TEMP)*EXP(E/TEMP)**2                        &
     &          + F*EXP(G/TEMP)*EXP(E/TEMP)**2*EXP(EX1/TEMP)           &
     &          + CC*EXP(D/TEMP)*EXP(E/TEMP)                           &
     &          + A*EXP(B/TEMP)*EXP(EX1/TEMP)                          &
     &          + CC*EXP(D/TEMP)*EXP(EX1/TEMP)*EXP(J/TEMP)             &
     &          + H*EXP(I/TEMP)*EXP(E/TEMP) + T/TEMP/TEMP*EXP(E/TEMP)) &
     &          + 4.4E+17/TEMP*Q)/60.)

      RETURN
      END

      
      
      REAL*8 FUNCTION K8377(TEMP)

      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 

      K8377= DBLE((4.4E+17*TEMP*(A*EXP(B/TEMP)*EXP(EX1/TEMP)  &
     &          + CC*EXP(D/TEMP)*EXP(EX1/TEMP)*EXP(E/TEMP)    &
     &          + CC*EXP(D/TEMP)*EXP(E/TEMP)*EXP(E/TEMP)      &
     &          + F*EXP(G/TEMP)*EXP(E/TEMP)                   &
     &          + A*EXP(B/TEMP)                               &
     &          + EX5/TEMP/TEMP                               &
     &          + CC*EXP(D/TEMP)*EXP(E/TEMP)*EXP(EX2/TEMP)    &
     &          + T/TEMP/TEMP*EXP(E/TEMP)))/60.)

      RETURN
      END
       


      REAL*8 FUNCTION K8378(TEMP)

      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      K8378= DBLE((4.4E+17*TEMP*(A*EXP(B/TEMP)                &
     &         + CC*EXP(D/TEMP)*EXP(E/TEMP)                   &
     &         + CC*EXP(D/TEMP)*EXP(E/TEMP)*EXP(E/TEMP)       &
     &         + F*EXP(G/TEMP)*(EXP(E/TEMP)**2)*EXP(EX1/TEMP) &
     &         + A*EXP(B/TEMP)*EXP(EX1/TEMP)                  &
     &         + F*EXP(G/TEMP)*EXP(EX4/TEMP)*EXP(EX1/TEMP)    &
     &         + T/TEMP/TEMP                                  &
     &         + CC*EXP(D/TEMP)*EXP(E/TEMP)                   &
     &         + Q/TEMP/TEMP))/60.) 

      RETURN
      END
      
      
      
      REAL*8 FUNCTION KS12(TEMP,VAR)
      
      use cacm3_Parameters
!      use cacm3_Global
      REAL(KIND=dp) TEMP 
      
      REAL*8 CACID, K
      REAL(KIND=dp), DIMENSION(NVAR), INTENT(IN)  :: VAR
      INTEGER ii
      INTEGER naers12, aers12_spc

      K = 1.5d-32*exp(14770./TEMP)*4.4d+17/TEMP/1000.d+0/60.d+0
      cacid=0.0
!      do ii=1,naers12
!        cacid=cacid+c(aers12_spc(ii))
!      enddo
!      CACID = C(137) + C(81) + C(82) + C(83) + C(84) + C(85)  &
!     &      + C(86) + C(87) + C(88) + C(89) + C(90) + C(91)   &
!     &      + C(92) + C(93) + C(94) + C(95) + C(96) + C(97)   &
      CACID = VAR(184) + VAR(31) + VAR(32) + VAR(33) + VAR(34) + VAR(35)  &
           + VAR(36) + VAR(37) + VAR(38) + VAR(39) + VAR(40) + VAR(41)    &
           + VAR(42) + VAR(43) + VAR(44) + VAR(45) + VAR(46) + VAR(47)   
      
      KS12 = DBLE(K*CACID)
      
      RETURN
      END

      REAL*8 FUNCTION K8405(II,TEMP)
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      INTEGER II
      REAL*8 CF_NC, CF_C, Y298, MO, HF1, CF1, CF2
     
      CF_NC = 10.0
      CF_C = 0.3
      Y298 = CF_A*EXP(CF_B*CF_NC)
      MO = 7.33853E+21/TEMP
      HF1 = 0.5*(CF_C*(Y298*MO)/(1.0+(Y298*MO/CF_YI298/(TEMP/298.0)   &
     &         **(-1.*CF_MINF)))*CF_F**(1.0+(LOG10(Y298*MO/CF_YI298/  &
     &         (TEMP/298.0)**(-1.*CF_MINF)))**2)**(-1)) + 0.5

      CF1 = HF1/(1.0 + HF1)
      CF2 = 1.0 - CF1
      
      IF (II .EQ. 1) THEN
      K8405 = DBLE(8.89E-13*EXP(180.2/TEMP)*4.4E17/TEMP/60.*CF1)
      ELSE
      K8405 = DBLE(8.89E-13*EXP(180.2/TEMP)*4.4E17/TEMP/60.*CF2)
      ENDIF
      
      RETURN
      END
            
      
      
      REAL*8 FUNCTION K8414(TEMP)
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      K8414 =DBLE( 4.4E+17*TEMP*EXP(E/TEMP)*(A*EXP(B/TEMP) *       &
     &             EXP(K/TEMP)*EXP((-1.*E)/TEMP) + CC*EXP(D/TEMP)  &
     &             *EXP(K/TEMP) + CC*EXP(D/TEMP)*EXP(E/TEMP) +     &
     &             F*EXP(G/TEMP)*EXP(2.*E/TEMP) + F*EXP(G/TEMP) +  &
     &             2.*A*EXP(B/TEMP) + F*EXP(G/TEMP)*EXP(K/TEMP)*   &
     &             EXP(J/TEMP) + P/TEMP**2 + H*EXP(I/TEMP))/60.)
                 
      RETURN
      END
      
      
      
      REAL*8 FUNCTION K8415(TEMP)
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      
      REAL K61, K60, K309
      
      K309 =  4.4E+17*TEMP*EXP(E/TEMP)*(A*EXP(B/TEMP) *            &
     &             EXP(K/TEMP)*EXP((-1.*E)/TEMP) + CC*EXP(D/TEMP)  &
     &             *EXP(K/TEMP) + CC*EXP(D/TEMP)*EXP(E/TEMP) +     &
     &             F*EXP(G/TEMP)*EXP(2.*E/TEMP) + F*EXP(G/TEMP) +  &
     &             2.*A*EXP(B/TEMP) + F*EXP(G/TEMP)*EXP(K/TEMP)*   &
     &             EXP(J/TEMP) + P/TEMP**2 + H*EXP(I/TEMP))
      K61 = 1.32E+05/TEMP*EXP(-1427.0/TEMP)
      K60 = 3.039E+06/TEMP*EXP(250./TEMP)   
      
      K8415 = DBLE(K309*K61/K60/60.)
      
      RETURN
      END

      
      
      REAL*8 FUNCTION K8505(II,TEMP)
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      INTEGER II
      REAL*8 CF_NC, CF_C, Y298, MO, HF1, CF1, CF2
     
      CF_NC = 10.0
      CF_C = 0.3
      Y298 = CF_A*EXP(CF_B*CF_NC)
      MO = 7.33853E+21/TEMP
      HF1 = 0.5*(CF_C*(Y298*MO)/(1.0+(Y298*MO/CF_YI298/(TEMP/298.0)   &
     &         **(-1.*CF_MINF)))*CF_F**(1.0+(LOG10(Y298*MO/CF_YI298/  &
     &         (TEMP/298.0)**(-1.*CF_MINF)))**2)**(-1)) + 0.5

      CF1 = HF1/(1.0 + HF1)
      CF2 = 1.0 - CF1
      
      IF (II .EQ. 1) THEN
      K8505 = DBLE(8.89E-13*EXP(180.2/TEMP)*4.4E17/TEMP/60.*CF1)
      ELSE
      K8505 = DBLE(8.89E-13*EXP(180.2/TEMP)*4.4E17/TEMP/60.*CF2)
      ENDIF
      
      RETURN
      END
      
      
      
      REAL*8 FUNCTION K8511(II,TEMP)
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      INTEGER II
      REAL*8 CF_NC, CF_C, Y298, MO, HF1, CF1, CF2
     
      CF_NC = 9.0
      CF_C = 0.4
      Y298 = CF_A*EXP(CF_B*CF_NC)
      MO = 7.33853E+21/TEMP
      HF1 = CF_C*(Y298*MO)/(1.0+(Y298*MO/CF_YI298/(TEMP/298.0)        &
     &         **(-1.*CF_MINF)))*CF_F**(1.0+(LOG10(Y298*MO/CF_YI298/  &
     &         (TEMP/298.0)**(-1.*CF_MINF)))**2)**(-1)

      CF1 = HF1/(1.0 + HF1)
      CF2 = 1.0 - CF1
      
      IF (II .EQ. 1) THEN
      K8511 = DBLE(1.05E-12*EXP(180.2/TEMP)*4.4E17/TEMP/60.*CF1)
      ELSE
      K8511 = DBLE(1.05E-12*EXP(180.2/TEMP)*4.4E17/TEMP/60.*CF2)
      ENDIF
      
      RETURN
      END
      
      
      
      
      REAL*8 FUNCTION K8520(TEMP)
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      
      K8520 = DBLE(4.4E+17*TEMP*(H*EXP(I/TEMP)*EXP(E/TEMP) +             &
     &             CC*EXP(D/TEMP)*EXP(J/TEMP) + Q/TEMP**2 + P/TEMP**2    &
     &             + F*EXP(G/TEMP) + 2.*A*EXP(B/TEMP)*EXP(E/TEMP))/60.)
      
      RETURN
      END
      
      
      
      REAL*8 FUNCTION K8521(TEMP)
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      
      REAL K61, K60, K322
      K322 = 4.4E+17*TEMP*(H*EXP(I/TEMP)*EXP(E/TEMP) +                  &
     &             CC*EXP(D/TEMP)*EXP(J/TEMP) + Q/TEMP**2 + P/TEMP**2   &
     &             + F*EXP(G/TEMP) + 2.*A*EXP(B/TEMP)*EXP(E/TEMP))
      K61 = 1.32E+05/TEMP*EXP(-1427.0/TEMP)
      K60 = 3.039E+06/TEMP*EXP(250/TEMP)
      
      K8521 = DBLE(K322*K61/K60/60.)
      
      RETURN
      END



      REAL*8 FUNCTION K8607(II,TEMP)
      
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      REAL*8 CF_NC, CF_C, Y298, MO, HF1, CF1, CF2
      INTEGER II
      
      CF_NC = 5.0
      CF_C = 0.3
      MO = 7.33853E+21/TEMP
      Y298 = CF_A*EXP(CF_B*CF_NC)
      HF1 = CF_C*(Y298*MO)/(1.0+(Y298*MO/CF_YI298/(TEMP/298.0)       &
     &        **(-1.*CF_MINF)))*CF_F**(1.0+(LOG10(Y298*MO/CF_YI298/  &
     &        (TEMP/298.0)**(-1.*CF_MINF)))**2)**(-1)

      CF1 = HF1/(1.0+HF1)
      CF2 = 1.0 - CF1

      IF (II .EQ. 1) THEN
      K8607 = DBLE(2.08E-12*EXP(180.2/TEMP)*4.4E+17/TEMP/60.*CF1)
      ELSE
      K8607 = DBLE(2.08E-12*EXP(180.2/TEMP)*4.4E+17/TEMP/60.*CF2)
      END IF
      
      RETURN
      END      


      
      REAL*8 FUNCTION K8704(II,TEMP)
      use cacm3_Parameters
!      use cacm3_Global
      include 'user_Parameters.h'
      REAL(KIND=dp) TEMP 
      INTEGER II
      REAL*8 CF_NC, CF_C, Y298, MO, HF1, CF1, CF2
     
      CF_NC = 10.0
      CF_C = 0.3
      Y298 = CF_A*EXP(CF_B*CF_NC)
      MO = 7.33853E+21/TEMP
      HF1 = 0.5*(CF_C*(Y298*MO)/(1.0+(Y298*MO/CF_YI298/(TEMP/298.0)   &
     &         **(-1.*CF_MINF)))*CF_F**(1.0+(LOG10(Y298*MO/CF_YI298/  &
     &         (TEMP/298.0)**(-1.*CF_MINF)))**2)**(-1)) + 0.5

      CF1 = HF1/(1.0 + HF1)
      CF2 = 1.0 - CF1
      
      IF (II .EQ. 1) THEN
      K8704 = DBLE(1.40E-12*EXP(180.2/TEMP)*4.4E17/TEMP/60.*CF1)
      ELSE
      K8704 = DBLE(1.40E-12*EXP(180.2/TEMP)*4.4E17/TEMP/60.*CF2)
      ENDIF
      
      RETURN
      END
      

      REAL*8 FUNCTION TROEPOW( A0,B0,C0,A1,B1,C1,CF,TEMP)
      REAL A0,B0,C0,A1,B1,C1,CF
      REAL(kind=dp) K0, K1, KR, NC, F    
      REAL(kind=dp) TEMP    
      REAL*8 Molc2ppm
      Parameter(Molc2ppm = 2.46E13)    
      REAL(kind=dp), PARAMETER :: CFACTOR=2.5E+19 
      K0 = DBLE(A0) * EXP(DBLE(B0)/TEMP) * (TEMP/300.0_dp)**DBLE(C0)
      K1 = DBLE(A1) * EXP(DBLE(B1)/TEMP) * (TEMP/300.0_dp)**DBLE(C1)
      K0 = K0*CFACTOR
      KR = K0/K1
      NC = 0.75_dp-1.27_dp*(LOG10(DBLE(CF)))
      F  = 10.0_dp**(LOG10(DBLE(CF))/(1+(LOG10(KR)/NC)**2))
      TROEPOW = K0*K1*F/(K0+K1) * Molc2ppm
      END FUNCTION TROEPOW



! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_RCONST - function to update rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_RCONST ( &
                      j, nj,  &
                      RCONST ,  &
                      var, &
                      Pj_no2 , Pj_no3o2 , Pj_no3o , Pj_o33p , Pj_o31d , &
                      Pj_hno2 , Pj_h2o2 , Pj_ooh1 , Pj_ooh2 , Pj_rpr2301, &
                      Pj_ch2or , Pj_ch2om , Pj_ch3cho , Pj_ald2 , Pj_ch3coc2h5 , &
                      Pj_ooh6101 , Pj_ooh6102 , Pj_hac , Pj_ap6101 , Pj_ap6102 , &
                      Pj_nald , Pj_hpald , Pj_pacald , Pj_macr , Pj_rp6301 , &
                      Pj_ooh6301 , Pj_hcochob , Pj_rp7102 , Pj_ch3cocho , Pj_pina , &
                      Pj_nrpa , Pj_edlm , Pj_lmkt , Pj_rpr8401 , Pj_rpr8501 , &
                      Pj_ooh8601 , Pj_ooh8602 , &
                      Pj_1co2ooh, Pj_3ooh4co,  Pj_3ooh4oh, Pj_1oh2ooh, Pj_mvk3oh4co, & 
                      Pj_mvk3co4oh, Pj_1co4ooh, Pj_1ooh4co, Pj_mcrenol, Pj_mvkenol,  &
                      Pj_mvk3ooh4co, Pj_1n4co, Pj_1co4n, Pj_3co4n, &
                      C_M, C_H2O, TEMP)

! Begin INLINED RCONST
   IMPLICIT NONE

   INTEGER, INTENT (IN ) :: nj 

    REAL(KIND=dp), DIMENSION(nj), INTENT(IN)  :: j

    REAL(KIND=dp), DIMENSION(NREACT), INTENT(OUT)  :: RCONST
    REAL(KIND=dp), DIMENSION(NVAR), INTENT(IN)  :: VAR

    REAL(KIND=dp), INTENT(IN)  :: C_M, C_H2O, TEMP


    INTEGER, INTENT(IN) ::&
                      Pj_no2 , Pj_no3o2 , Pj_no3o , Pj_o33p , Pj_o31d , &
                      Pj_hno2 , Pj_h2o2 , Pj_ooh1 , Pj_ooh2 , Pj_rpr2301, &
                      Pj_ch2or , Pj_ch2om , Pj_ch3cho , Pj_ald2 , Pj_ch3coc2h5 , &
                      Pj_ooh6101 , Pj_ooh6102 , Pj_hac , Pj_ap6101 , Pj_ap6102 , &
                      Pj_nald , Pj_hpald , Pj_pacald , Pj_macr , Pj_rp6301 , &
                      Pj_ooh6301 , Pj_hcochob , Pj_rp7102 , Pj_ch3cocho , Pj_pina , &
                      Pj_nrpa , Pj_edlm , Pj_lmkt , Pj_rpr8401 , Pj_rpr8501 , &
                      Pj_ooh8601 , Pj_ooh8602, &
                      Pj_1co2ooh, Pj_3ooh4co,  Pj_3ooh4oh, Pj_1oh2ooh, Pj_mvk3oh4co, & 
                      Pj_mvk3co4oh, Pj_1co4ooh, Pj_1ooh4co, Pj_mcrenol, Pj_mvkenol,  &
                      Pj_mvk3ooh4co, Pj_1n4co, Pj_1co4n, Pj_3co4n

    REAL(KIND=dp), PARAMETER :: mol2ppm = 2.46E13


! End INLINED RCONST

  RCONST(1) = j(Pj_no2) !8.29d-3
  RCONST(2) = AR(7.5454,-3.8,0.,TEMP)
  RCONST(3) = (AR(6.5E-12,0.0,119.8,TEMP))
  RCONST(4) = (AR2(9.0E-32,2.0,2.2E-11,0.,0.8,TEMP))
  RCONST(5) = (AR(1.8E-12,0.0,-1368.9,TEMP))
  RCONST(6) = (AR(1.4E-13,0.0,-2471.1,TEMP))
  RCONST(7) = (AR(1.8E-11,0.0,110.7,TEMP))
  RCONST(8) = (AR(5.09E-18,-1.0,528.4,TEMP))
  RCONST(9) = (AR2(2.8E-30,3.5,2.0E-12,0.2,0.45,TEMP))
  RCONST(10) = (K10(TEMP))
  RCONST(11) = (AR(2.59E-22,0.0,0.0,TEMP))
  RCONST(12) = (AR(4.5E-14,0.0,-1258.2,TEMP))
  RCONST(13) = j(Pj_no3o2) !(1.87d-2)
  RCONST(14) = j(Pj_no3o)  !(1.703d-1)
  RCONST(15) = j(Pj_o33p)!(4.57d-4)
  RCONST(16) = j(Pj_o31d)!(3.78d-5)
  RCONST(17) = (AR(2.2E-10,0.0,0.0,TEMP))
  RCONST(18) = (AR(2.091E-5,0.0,95.6,TEMP))
  RCONST(19) = (AR2(7.0E-31,2.6,3.6E-11,0.1,0.6,TEMP))
  RCONST(20) = j(Pj_hno2)!(1.63d-3)
  RCONST(21) = (AR(4.0E-24,0.0,0.0,TEMP))
  RCONST(22) = (K22(TEMP))
  RCONST(23) = (K23(TEMP))
  RCONST(24) = (K24(TEMP))
  RCONST(25) = (AR(1.9E-12,0.0,-1001.5,TEMP))
  RCONST(26) = (AR(3.41E-12,0.0,271.8,TEMP))
  RCONST(27) = (AR2(1.8E-31,3.2,4.7E-12,0.0,0.6,TEMP))
  RCONST(28) = (K28(TEMP))
  RCONST(29) = (AR(1.5E-12,0.0,362.4,TEMP))
  RCONST(30) = (AR(1.4E-14,0.0,-598.9,TEMP))
  RCONST(31) = (K31())
  RCONST(32) = (K32())
  RCONST(33) = (AR(4.0E-12,0.0,0.0,TEMP))
  RCONST(34) = (AR(8.0E-12,0.0,-2058.4,TEMP))
  RCONST(35) = (AR2(4.1E-31,3.3,2.0E-12,0.0,0.45,TEMP))
  RCONST(36) = j(Pj_h2o2)!(7.53d-6)
  RCONST(37) = (AR(2.91E-12,0.0,-161.0,TEMP))
  RCONST(38) = (AR(6.75E-6,-2.6,0.0,TEMP))
  RCONST(39) = (AR(2.7E-12,0.0,261.7,TEMP))
  RCONST(40) = (AR(2.0E-11,0.0,0.0,TEMP))
  RCONST(41) = (AR(8.5E-13,0.0,-2450.9,TEMP))
  RCONST(42) = (AR(4.8E-11,0.0,251.6,TEMP)) !/11.4 ! test OH+HO2 
  RCONST(43) = j(Pj_ooh1) !constant rate coefficient
  RCONST(44) = (AR(1.9E-12,0.0,190.,TEMP))
  RCONST(45) = (AR(1.0E-12,0.0,190.,TEMP))
  RCONST(46) = j(Pj_ooh2) !constant rate coefficient
  RCONST(47) = (AR(1.9E-12,0.0,190.,TEMP))
  RCONST(48) = (AR(1.0E-12,0.0,190.,TEMP))
  RCONST(49) = (AR(4.2E-12,0.0,181.2,TEMP))
  RCONST(50) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(51) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(52) = (AR(2.66E-12,0.0,-1800.2,TEMP))
  RCONST(53) = (AR(4.09E-12,0.0,180.2,TEMP))
  RCONST(54) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(55) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(56) = (AR(1.52E-17,2.0,-498.,TEMP))
  RCONST(57) = (AR(4.09E-12,0.0,180.2,TEMP))
  RCONST(58) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(59) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(60) = (AR(3.91E-12,0.0,0.0,TEMP))
  RCONST(61) = (K1302(1,TEMP))
  RCONST(62) = (K1302(2,TEMP))
  RCONST(63) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(64) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(65) = (K1401(TEMP))
  RCONST(66) = (K1402(1,TEMP))
  RCONST(67) = (K1402(2,TEMP))
  RCONST(68) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(69) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(70) = (K1402(1,TEMP))
  RCONST(71) = (K1402(2,TEMP))
  RCONST(72) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(73) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(74) = (AR(0.077E-10,0.0,0.0,TEMP))
  RCONST(75) = (AR(0.054E-10,0.0,0.0,TEMP))
  RCONST(76) = (K1501(TEMP))
  RCONST(77) = (K1502(1,TEMP))
  RCONST(78) = (K1502(2,TEMP))
  RCONST(79) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(80) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(81) = (K1502(1,TEMP))
  RCONST(82) = (K1502(2,TEMP))
  RCONST(83) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(84) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(85) = (AR(0.188E-10,0.0,0.0,TEMP))
  RCONST(86) = (AR(0.278E-10,0.0,0.0,TEMP))
  RCONST(87) = (AR(1.96E-12,0.0,437.8,TEMP))
  RCONST(88) = (AR(4.89E-18,2.0,-2282.3,TEMP))
  RCONST(89) = (AR(9.14E-15,0.0,-2580.3,TEMP))
  RCONST(90) = (AR(7.3E-13,0.0,0.0,TEMP))
  RCONST(91) = (AR(4.1E-12,0.0,180.2,TEMP))
  RCONST(92) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(93) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(94) = (AR(4.1E-12,0.0,180.2,TEMP))
  RCONST(95) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(96) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(97) = (AR(3.45E-12,0.0,180.2,TEMP))
  RCONST(98) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(99) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(100) = (AR(5.86E-12,0.0,500.3,TEMP))
  RCONST(101) = (AR(1.0E-13,0.0,-800.2,TEMP))
  RCONST(102) = (AR(1.0E-17,0.0,0.0,TEMP))
  RCONST(103) = (AR(4.66E-12,0.0,0.0,TEMP))
  RCONST(104) = (AR(2.45E-12,0.0,180.2,TEMP))
  RCONST(105) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(106) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(107) = (AR(2.45E-12,0.0,180.2,TEMP))
  RCONST(108) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(109) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(110) = (K2301(TEMP))
  RCONST(111) = (K2302(TEMP))
  RCONST(112) = (K2303(TEMP))
  RCONST(113) = (K2304(TEMP))
  RCONST(114) = (AR(1.05E-12,0.0,180.2,TEMP))
  RCONST(115) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(116) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(117) = (K2308(TEMP))
  RCONST(118) = (K2309(TEMP))
  RCONST(119) = j(Pj_rpr2301) !constant rate coefficient
  RCONST(120) = (AR(1.11E-11,0.0,180.2,TEMP))
  RCONST(121) = (AR2(9.7E-29,5.6,9.3E-12,1.5,0.6,TEMP))
  RCONST(122) = (KPAN(TEMP))
  RCONST(123) = (AR(9.74E-13,0.0,800.2,TEMP))
  RCONST(124) = (AR(1.0E-11,0.0,0.0,TEMP))
  RCONST(125) = j(Pj_ch2or) !constant rate coefficient
  RCONST(126) = j(Pj_ch2om) !constant rate coefficient
  RCONST(127) = (AR(1.2E-14,1.0,286.9,TEMP))
  RCONST(128) = (AR(2.0E-12,0.0,-2430.8,TEMP))
  RCONST(129) = j(Pj_ch3cho)!constant rate coefficient
  RCONST(130) = (AR(5.60E-12,0.0,312.0,TEMP))
  RCONST(131) = (AR(1.40E-12,0.0,-1862.0,TEMP))
  RCONST(132) = (AR(1.11E-11,0.0,180.2,TEMP))
  RCONST(133) = (AR2(9.7E-29,5.6,9.3E-12,1.5,0.6,TEMP))
  RCONST(134) = (KPAN(TEMP))
  RCONST(135) = (AR(9.74E-13,0.0,800.2,TEMP))
  RCONST(136) = (AR(1.0E-11,0.0,0.0,TEMP))
  RCONST(137) = j(Pj_ald2)!constant rate coefficient
  RCONST(138) = (AR(6.91E-12,0.0,250.,TEMP))
  RCONST(139) = (AR(3.0E-13,0.0,-1427.,TEMP))
  RCONST(140) = (AR(1.11E-11,0.0,180.2,TEMP))
  RCONST(141) = (AR2(9.7E-29,5.6,9.3E-12,1.5,0.6,TEMP))
  RCONST(142) = (KPAN(TEMP))
  RCONST(143) = (AR(9.74E-13,0.0,800.2,TEMP))
  RCONST(144) = (AR(1.0E-11,0.0,0.0,TEMP))
  RCONST(145) = (AR(6.0E-18,2.0,170.1,TEMP))
  RCONST(146) = (K4201(1,TEMP))
  RCONST(147) = (K4201(2,TEMP))
  RCONST(148) = (K4301(TEMp))
  RCONST(149) = (AR(4.91E-12,0.0,0.0,TEMP))
  RCONST(150) = j(Pj_ch3coc2h5)!constant rate coefficient
  RCONST(151) = (AR(2.45E-12,0.0,180.2,TEMP))
  RCONST(152) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(153) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(154) = (K5201(TEMP))
  RCONST(155) = j(Pj_ch3coc2h5)!constant rate coefficient
  RCONST(156) = (AR(1.48E-12,0.0,180.2,TEMP))
  RCONST(157) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(158) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(159) = (AR(3.27E-11,0.0,0.0,TEMP))
  RCONST(160) = (AR(0.945E-10,0.0,0.0,TEMP))
  RCONST(161) = (AR(5.1E-11,0.0,0.0,TEMP))
  RCONST(162) = (K7104(1,TEMP))
  RCONST(163) = (K7104(2,TEMP))
  RCONST(164) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(165) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(166) = (K7107(TEMP))
  RCONST(167) = (AR(1.05E-12,0.0,180.2,TEMP))
  RCONST(168) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(169) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(170) = (AR(1.05E-12,0.0,180.2,TEMP))
  RCONST(171) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(172) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(173) = (K7114(TEMP))
  RCONST(174) = (K7115(TEMP))
  RCONST(175) = j(Pj_rp7102)!constant rate coefficient
  RCONST(176) = (AR(1.72E-11,0.0,0.0,TEMP))
  RCONST(177) = (AR(1.4E-12,0.0,-1897.3,TEMP))
  RCONST(178) = j(Pj_ch3cocho)!constant rate coefficient
  RCONST(179) = (AR(1.11E-11,0.0,180.2,TEMP))
  RCONST(180) = (AR2(9.7E-29,5.6,9.3E-12,1.5,0.6,TEMP))
  RCONST(181) = (KPAN(TEMP))
  RCONST(182) = (AR(9.74E-13,0.0,800.2,TEMP))
  RCONST(183) = (AR(1.0E-11,0.0,0.0,TEMP))
  RCONST(184) = (AR(0.331E-10,0.0,0.0,TEMP))
  RCONST(185) = (K7201(TEMP))
  RCONST(186) = (AR(0.945E-10,0.0,0.0,TEMP))
  RCONST(187) = (AR(5.1E-11,0.0,0.0,TEMP))
  RCONST(188) = (K7203(TEMP))
  RCONST(189) = (AR(8.89E-13,0.0,180.2,TEMP))
  RCONST(190) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(191) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(192) = (AR(8.89E-13,0.0,180.2,TEMP))
  RCONST(193) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(194) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(195) = (AR(3.77E-12,0.0,0.0,TEMP))
  RCONST(196) = (K7302(TEMP))
  RCONST(197) = (AR(5.1E-11,0.0,0.0,TEMP))
  RCONST(198) = (AR(0.945E-10,0.0,0.0,TEMP))
  RCONST(199) = (AR(5.1E-11,0.0,0.0,TEMP))
  RCONST(200) = (K7306(1,TEMP))
  RCONST(201) = (K7306(2,TEMP))
  RCONST(202) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(203) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(204) = (K7107(TEMP))
  RCONST(205) = (AR(1.25E-12,0.0,180.2,TEMP))
  RCONST(206) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(207) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(208) = (AR(1.25E-12,0.0,180.2,TEMP))
  RCONST(209) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(210) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(211) = (AR(3.77E-12,0.0,0.0,TEMP))
  RCONST(212) = (AR(2.30E-11,0.0,151.0,TEMP))
  RCONST(213) = (AR(1.29E-11,0.0,0.0,TEMP))
  RCONST(214) = (K7319(TEMP))
  RCONST(215) = (K7320(TEMP))
  RCONST(216) = (AR(2.202E-10,0.0,0.0,TEMP))
  RCONST(217) = (AR(1.4E-12,0.0,-1872.2,TEMP))
  RCONST(218) = (K7402(1,TEMP))
  RCONST(219) = (K7402(2,TEMP))
  RCONST(220) = (K7402(3,TEMP))
  RCONST(221) = (K7402(4,TEMP))
  RCONST(222) = (AR(0.945E-10,0.0,0.0,TEMP))
  RCONST(223) = (AR(5.1E-11,0.0,0.0,TEMP))
  RCONST(224) = (K7405(1,TEMP))
  RCONST(225) = (K7405(2,TEMP))
  RCONST(226) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(227) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(228) = (K7107(TEMP))
  RCONST(229) = (AR(1.25E-12,0.0,180.2,TEMP))
  RCONST(230) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(231) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(232) = (AR(1.25E-12,0.0,180.2,TEMP))
  RCONST(233) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(234) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(235) = (AR(1.29E-11,0.0,0.0,TEMP))
  RCONST(236) = (AR(1.29E-11,0.0,0.0,TEMP))
  RCONST(237) = (K7417(TEMP))
  RCONST(238) = (AR(1.29E-11,0.0,0.0,TEMP))
  RCONST(239) = (K7419(TEMP))
  RCONST(240) = (K7420(TEMP))
  RCONST(241) = (AR(0.132E-10,0.0,0.0,TEMP))
  RCONST(242) = (AR(1.05E-12,0.0,0.0,TEMP))
  RCONST(243) = (AR(0.945E-10,0.0,0.0,TEMP))
  RCONST(244) = (AR(5.1E-11,0.0,0.0,TEMP))
  RCONST(245) = (K7504(1,TEMP))
  RCONST(246) = (K7504(2,TEMP))
  RCONST(247) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(248) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(249) = (K7107(TEMP))
  RCONST(250) = (AR(1.25E-12,0.0,180.2,TEMP))
  RCONST(251) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(252) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(253) = (AR(1.25E-12,0.0,180.2,TEMP))
  RCONST(254) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(255) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(256) = (AR(0.014E-10,0.0,0.0,TEMP))
  RCONST(257) = (AR(7.7E-11,0.0,0.0,TEMP))
  RCONST(258) = (AR(0.945E-10,0.0,0.0,TEMP))
  RCONST(259) = (AR(5.1E-11,0.0,0.0,TEMP))
  RCONST(260) = (K7604(1,TEMP))
  RCONST(261) = (K7604(2,TEMP))
  RCONST(262) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(263) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(264) = (K7107(TEMP))
  RCONST(265) = (AR(6.32E-13,0.0,180.2,TEMP))
  RCONST(266) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(267) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(268) = (AR(6.32E-13,0.0,180.2,TEMP))
  RCONST(269) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(270) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(271) = (K7614(TEMP))
  RCONST(272) = (K7615(TEMP))
  RCONST(273) = (K7616(TEMP))
  RCONST(274) = (AR(0.777E-10,0.0,0.0,TEMP))
  RCONST(275) = (AR(3.2E-12,0.0,0.0,TEMP))
  RCONST(276) = (AR(2.08E-12,0.0,180.2,TEMP))
  RCONST(277) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(278) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(279) = (AR(1.21E-11,0.0,444.,TEMP))
  RCONST(280) = (AR(1.19E-12,0.0,490.,TEMP))
  RCONST(281) = (AR(1.01E-15,0.0,-732.,TEMP))
  RCONST(282) = (AR(3.2E-11,0.0,0.0,TEMP))
  RCONST(283) = (AR(8.8E-13,0.0,180.2,TEMP))
  RCONST(284) = (AR(1.82E-13,0.0,416.,TEMP))*2.7 !dw-zhao
  RCONST(285) = (AR(4.1E-13,0.0,790.,TEMP))
  RCONST(286) = (AR(8.8E-13,0.0,180.2,TEMP))
  RCONST(287) = (AR(1.82E-13,0.0,416.,TEMP))
  RCONST(288) = (AR(4.1E-13,0.0,790.,TEMP))
  RCONST(289) = (K8111(1,TEMP))
  RCONST(290) = (K8111(2,TEMP))
  RCONST(291) = (AR(1.82E-13,0.0,416.,TEMP))
  RCONST(292) = (AR(4.1E-13,0.0,790.,TEMP))
  RCONST(293) = (AR(8.8E-13,0.0,180.2,TEMP))
  RCONST(294) = (AR(1.82E-13,0.0,416.,TEMP))
  RCONST(295) = (AR(4.1E-13,0.0,790.,TEMP))
  RCONST(296) = (AR(8.8E-13,0.0,180.2,TEMP))
  RCONST(297) = (AR(1.82E-13,0.0,416.,TEMP))
  RCONST(298) = (AR(4.1E-13,0.0,790.,TEMP))
  RCONST(299) = j(Pj_pina)!constant rate coefficient
  RCONST(300) = (AR(9.1E-11,0.0,0.0,TEMP))
  RCONST(301) = (AR(5.4E-14,0.0,0.0,TEMP))
  RCONST(302) = (AR(1.11E-11,0.0,180.2,TEMP))
  RCONST(303) = (AR2(9.7E-29,5.6,9.3E-12,1.5,0.6,TEMP))
  RCONST(304) = (KPAN(TEMP))
  RCONST(305) = (AR(5.0E-12,0.0,0.0,TEMP))
  RCONST(306) = (AR(4.3E-13,0.0,1040.,TEMP))
  RCONST(307) = j(Pj_nrpa)!constant rate coefficient
  RCONST(308) = (AR(9.1E-11,0.0,0.0,TEMP))
  RCONST(309) = (AR(5.4E-14,0.0,0.0,TEMP))
  RCONST(310) = (AR(1.11E-11,0.0,180.2,TEMP))
  RCONST(311) = (AR2(9.7E-29,5.6,9.3E-12,1.5,0.6,TEMP))
  RCONST(312) = (KPAN(TEMP))
  RCONST(313) = (AR(5.0E-12,0.0,0.0,TEMP))
  RCONST(314) = (AR(4.3E-13,0.0,1040.,TEMP))
  RCONST(315) = (K8136(1,TEMP))
  RCONST(316) = (K8136(2,TEMP))
  RCONST(317) = (AR(1.82E-13,0.0,416.,TEMP))
  RCONST(318) = (AR(4.1E-13,0.0,790.,TEMP))
  RCONST(319) = (AR(1.11E-11,0.0,180.2,TEMP))
  RCONST(320) = (AR2(9.7E-29,5.6,9.3E-12,1.5,0.6,TEMP))
  RCONST(321) = (KPAN(TEMP))
  RCONST(322) = (AR(5.0E-12,0.0,0.0,TEMP))
  RCONST(323) = (AR(4.3E-13,0.0,1040.,TEMP))
  RCONST(324) = (K8144(TEMP))
  RCONST(325) = (K8145(TEMP))
  RCONST(326) = (K8146(TEMP))
  RCONST(327) = (KS12(TEMP,VAR))
  RCONST(328) = (KS12(TEMP,VAR))
  RCONST(329) = (KS12(TEMP,VAR))
  RCONST(330) = (KS12(TEMP,VAR))
  RCONST(331) = (KS12(TEMP,VAR))
  RCONST(332) = (KS12(TEMP,VAR))
  RCONST(333) = (AR(2.38E-11,0.0,357.,TEMP))
  RCONST(334) = (AR(2.51E-12,0.0,0.0,TEMP))
  RCONST(335) = (AR(1.5E-17,0.0,0.0,TEMP))
  RCONST(336) = (AR(2.7E-11,0.0,0.0,TEMP))
  RCONST(337) = (AR(8.8E-13,0.0,180.2,TEMP))
  RCONST(338) = (AR(1.82E-13,0.0,416.,TEMP))
  RCONST(339) = (AR(4.1E-13,0.0,790.,TEMP))
  RCONST(340) = (AR(8.8E-13,0.0,180.2,TEMP))
  RCONST(341) = (AR(1.82E-13,0.0,416.,TEMP))
  RCONST(342) = (AR(4.1E-13,0.0,790.,TEMP))
  RCONST(343) = (AR(1.43E-11,0.0,0.0,TEMP))
  RCONST(344) = (AR(1.05E-12,0.0,180.2,TEMP))
  RCONST(345) = (AR(1.82E-13,0.0,416.,TEMP))
  RCONST(346) = (AR(4.1E-13,0.0,790.,TEMP))
  RCONST(347) = (AR(1.71E-10,0.0,0.0,TEMP))
  RCONST(348) = (AR(1.22E-11,0.0,0.0,TEMP))
  RCONST(349) = (AR(2.00E-16,0.0,0.0,TEMP))
  RCONST(350) = (AR(7.2E-11,0.0,0.0,TEMP))
  RCONST(351) = (AR(8.8E-13,0.0,180.2,TEMP))
  RCONST(352) = (AR(1.82E-13,0.0,416.0,TEMP))*2.7 !dw
  RCONST(353) = (AR(4.1E-13,0.0,790.,TEMP))
  RCONST(354) = (AR(8.8E-13,0.0,180.2,TEMP))
  RCONST(355) = (AR(1.82E-13,0.0,416.0,TEMP))*2.7 !dw
  RCONST(356) = (AR(4.1E-13,0.0,790.,TEMP))
  RCONST(357) = (AR(8.8E-13,0.0,180.2,TEMP))
  RCONST(358) = (AR(1.82E-13,0.0,416.0,TEMP))
  RCONST(359) = (AR(4.1E-13,0.0,790.,TEMP))
  RCONST(360) = (AR(8.8E-13,0.0,180.2,TEMP))
  RCONST(361) = (AR(1.82E-13,0.0,416.0,TEMP))
  RCONST(362) = (AR(4.1E-13,0.0,790.,TEMP))
  RCONST(363) = (AR(8.8E-13,0.0,180.2,TEMP))
  RCONST(364) = (AR(1.82E-13,0.0,416.0,TEMP))
  RCONST(365) = (AR(4.1E-13,0.0,790.,TEMP))
  RCONST(366) = (AR(8.8E-13,0.0,180.2,TEMP))
  RCONST(367) = (AR(1.82E-13,0.0,416.0,TEMP))
  RCONST(368) = (AR(4.1E-13,0.0,790.,TEMP))
  RCONST(369) = (AR(1.05E-12,0.0,180.2,TEMP))
  RCONST(370) = (AR(1.82E-13,0.0,416.0,TEMP))
  RCONST(371) = (AR(4.1E-13,0.0,790.,TEMP))
  RCONST(372) = (AR(1.05E-12,0.0,180.2,TEMP))
  RCONST(373) = (AR(1.82E-13,0.0,416.0,TEMP))
  RCONST(374) = (AR(4.1E-13,0.0,790.,TEMP))
  RCONST(375) = (AR(1.11E-11,0.0,180.2,TEMP))
  RCONST(376) = (AR2(9.7E-29,5.6,9.3E-12,1.5,0.6,TEMP))
  RCONST(377) = (KPAN(TEMP))
  RCONST(378) = (AR(5.0E-12,0.0,0.0,TEMP))
  RCONST(379) = (AR(4.3E-13,0.0,1040.,TEMP))
  RCONST(380) = (AR(1.1E-10,0.0,0.0,TEMP))
  RCONST(381) = (AR(2.5E-13,0.0,0.0,TEMP))
  RCONST(382) = (AR(8.3E-18,0.0,0.0,TEMP))
  RCONST(383) = j(Pj_edlm)!constant rate coefficient
  RCONST(384) = (AR(8.8E-13,0.0,180.2,TEMP))
  RCONST(385) = (AR(1.82E-13,0.0,416.0,TEMP))
  RCONST(386) = (AR(4.1E-13,0.0,790.,TEMP))
  RCONST(387) = (AR(8.8E-13,0.0,180.2,TEMP))
  RCONST(388) = (AR(1.82E-13,0.0,416.0,TEMP))
  RCONST(389) = (AR(4.1E-13,0.0,790.,TEMP))
  RCONST(390) = (AR(1.05E-12,0.0,180.2,TEMP))
  RCONST(391) = (AR(1.82E-13,0.0,416.0,TEMP))
  RCONST(392) = (AR(4.1E-13,0.0,790.,TEMP))
  RCONST(393) = j(Pj_lmkt) !constant rate coefficient
  RCONST(394) = (AR(1.29E-10,0.0,0.0,TEMP))
  RCONST(395) = (AR(1.05E-11,0.0,0.0,TEMP))
  RCONST(396) = (AR(1.50E-16,0.0,0.0,TEMP))
  RCONST(397) = (AR(5.43E-11,0.0,0.0,TEMP))
  RCONST(398) = (AR(1.05E-12,0.0,180.2,TEMP))
  RCONST(399) = (AR(1.82E-13,0.0,416.0,TEMP))
  RCONST(400) = (AR(4.1E-13,0.0,790.,TEMP))
  RCONST(401) = (AR(1.05E-12,0.0,180.2,TEMP))
  RCONST(402) = (AR(1.82E-13,0.0,416.0,TEMP))
  RCONST(403) = (AR(4.1E-13,0.0,790.,TEMP))
  RCONST(404) = (AR(1.24E-12,0.0,180.2,TEMP))
  RCONST(405) = (AR(1.82E-13,0.0,416.0,TEMP))
  RCONST(406) = (AR(4.1E-13,0.0,790.,TEMP))
  RCONST(407) = (AR(1.05E-12,0.0,180.2,TEMP))
  RCONST(408) = (AR(1.82E-13,0.0,416.0,TEMP))
  RCONST(409) = (AR(4.1E-13,0.0,790.,TEMP))
  RCONST(410) = (AR(1.05E-12,0.0,180.2,TEMP))
  RCONST(411) = (AR(1.82E-13,0.0,416.0,TEMP))
  RCONST(412) = (AR(4.1E-13,0.0,790.,TEMP))
  RCONST(413) = (AR(1.11E-11,0.0,180.2,TEMP))
  RCONST(414) = (AR2(9.7E-29,5.6,9.3E-12,1.5,0.6,TEMP))
  RCONST(415) = (KPAN(TEMP))
  RCONST(416) = (AR(5.0E-12,0.0,0.0,TEMP))
  RCONST(417) = (AR(4.3E-13,0.0,1040.,TEMP))
  RCONST(418) = (K8372(TEMP))
  RCONST(419) = (K8373(TEMP))
  RCONST(420) = (K8374(TEMP))
  RCONST(421) = (K8375(TEMP))
  RCONST(422) = (K8376(TEMP))
  RCONST(423) = (K8377(TEMP))
  RCONST(424) = (K8378(TEMP))
  RCONST(425) = (KS12(TEMP,VAR))
  RCONST(426) = (KS12(TEMP,VAR))
  RCONST(427) = (KS12(TEMP,VAR))
  RCONST(428) = (KS12(TEMP,VAR))
  RCONST(429) = (KS12(TEMP,VAR))
  RCONST(430) = (KS12(TEMP,VAR))
  RCONST(431) = (KS12(TEMP,VAR))
  RCONST(432) = (KS12(TEMP,VAR))
  RCONST(433) = (KS12(TEMP,VAR))
  RCONST(434) = (AR(1.7E-10,0.0,0.0,TEMP))
  RCONST(435) = (AR(1.46E-11,0.0,0.0,TEMP))
  RCONST(436) = (AR(2.5E-16,0.0,0.0,TEMP))
  RCONST(437) = (AR(1.35E-10,0.0,-500.3,TEMP))
  RCONST(438) = (K8405(1,TEMP))
  RCONST(439) = (K8405(2,TEMP))
  RCONST(440) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(441) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(442) = (AR(8.93E-13,0.0,180.2,TEMP))
  RCONST(443) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(444) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(445) = (AR(8.93E-13,0.0,180.2,TEMP))
  RCONST(446) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(447) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(448) = (K8414(TEMP))
  RCONST(449) = (K8415(TEMP))
  RCONST(450) = j(Pj_rpr8401) !constant rate coefficient
  RCONST(451) = (AR(1.11E-11,0.0,180.2,TEMP))
  RCONST(452) = (AR2(9.7E-29,5.6,9.3E-12,1.5,0.6,TEMP))
  RCONST(453) = (KPAN(TEMP))
  RCONST(454) = (AR(9.74E-13,0.0,800.2,TEMP))
  RCONST(455) = (AR(1.0E-11,0.0,0.0,TEMP))
  RCONST(456) = (KS12(TEMP,VAR))
  RCONST(457) = (AR(1.77E-10,0.0,0.0,TEMP))
  RCONST(458) = (AR(2.91E-11,0.0,0.0,TEMP))
  RCONST(459) = (AR(1.4E-16,0.0,0.0,TEMP))
  RCONST(460) = (AR(8.59E-11,0.0,0.0,TEMP))
  RCONST(461) = (K8505(1,TEMP))
  RCONST(462) = (K8505(2,TEMP))
  RCONST(463) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(464) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(465) = (AR(8.89E-13,0.0,180.2,TEMP))
  RCONST(466) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(467) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(468) = (K8511(1,TEMP))
  RCONST(469) = (K8511(2,TEMP))
  RCONST(470) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(471) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(472) = (AR(8.89E-13,0.0,180.2,TEMP))
  RCONST(473) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(474) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(475) = (AR(1.05E-12,0.0,180.2,TEMP))
  RCONST(476) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(477) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(478) = (K8520(TEMP))
  RCONST(479) = (K8521(TEMP))
  RCONST(480) = j(Pj_rpr8501)!constant rate coefficient
  RCONST(481) = j(Pj_rpr8501)!constant rate coefficient
  RCONST(482) = (AR(1.11E-11,0.0,180.2,TEMP)) 
  RCONST(483) = (AR2(9.7E-29,5.6,9.3E-12,1.5,0.6,TEMP))
  RCONST(484) = (KPAN(TEMP))
  RCONST(485) = (AR(9.74E-13,0.0,800.2,TEMP))
  RCONST(486) = (AR(1.0E-11,0.0,0.0,TEMP)) 
  RCONST(487) = (AR(0.907E-10,0.0,0.0,TEMP))
  RCONST(488) = (KS12(TEMP,VAR))
  RCONST(489) = (KS12(TEMP,VAR))
  RCONST(490) = (AR(6.26E-11,0.0,0.0,TEMP))
  RCONST(491) = (AR(9.30E-18,0.0,0.0,TEMP))
  RCONST(492) = (AR(1.4E-15,0.0,0.0,TEMP))
  RCONST(493) = (AR(2.45E-12,0.0,180.2,TEMP))
  RCONST(494) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(495) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(496) = (K8607(1,TEMP))
  RCONST(497) = (K8607(2,TEMP))
  RCONST(498) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(499) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(500) = (AR(2.45E-12,0.0,180.2,TEMP))
  RCONST(501) = (AR(1.0E-12,0.0,0.0,TEMP))
  RCONST(502) = (AR(1.5E-12,0.0,800.2,TEMP))
  RCONST(503) = j(Pj_ooh8601)!constant rate coefficient
  RCONST(504) = j(Pj_ooh8602)!constant rate coefficient
  RCONST(505) = (AR(1.9E-11,0.0,390.0,TEMP))
  RCONST(506) = (AR(1.9E-11,0.0,390.0,TEMP))
  RCONST(507) = (AR(3.8E-12,0.0,200.0,TEMP))
  RCONST(508) = (AR(3.8E-12,0.0,200.0,TEMP))
  RCONST(509) = (AR(1.94E-11,0.0,0.0,TEMP))
  RCONST(510) = 2.0E-10*mol2ppm!constant rate coefficient
  RCONST(511) = 1.20E-14*mol2ppm! constant rate coefficient
  RCONST(512) = 2.20E-11*mol2ppm!constant rate coefficient
  RCONST(513) = (K8704(1,TEMP))
  RCONST(514) = (K8704(2,TEMP))
  RCONST(515) = (AR(2.66E-13,0.0,1300.0,TEMP))
  RCONST(516) = 9.00E-14*mol2ppm !constant rate coefficient
  RCONST(517) = (AR(2.54E-12,0.0,360.0,TEMP))
  RCONST(518) = (AR(2.66E-13,0.0,1300.0,TEMP))
  RCONST(519) = 9.00E-14*mol2ppm !constant rate coefficient
  RCONST(520) = (AR(2.54E-12,0.0,360.0,TEMP))
  RCONST(521) = (AR(2.66E-13,0.0,1300.0,TEMP))
  RCONST(522) = 9.00E-14*mol2ppm !constant rate coefficient
  RCONST(523) = 3.20E-10*mol2ppm !constant rate coefficient
  RCONST(524) = 1.00E-15*mol2ppm!constant rate coefficient
 RCONST(525) = 2.20E-11*mol2ppm!constant rate coefficient
 RCONST(526) = 2.00E-10*mol2ppm!constant rate coefficient
 RCONST(527) = 1.20E-14*mol2ppm!constant rate coefficient
 RCONST(528) = 2.20E-11*mol2ppm!constant rate coefficient
  RCONST(529) = (AR(2.54E-12,0.0,360.0,TEMP))
  RCONST(530) = (AR(2.66E-13,0.0,1300.0,TEMP))
 RCONST(531) = 9.00E-14*mol2ppm !constant rate coefficient
  RCONST(532) = (AR(2.54E-12,0.0,360.0,TEMP))
  RCONST(533) = (AR(2.66E-13,0.0,1300.0,TEMP))
 RCONST(534) =  9.00E-14*mol2ppm !constant rate coefficient
  RCONST(535) = (AR(0.907E-10,0.0,0.0,TEMP))
  RCONST(536) = (ISO1(1.7E-11,390.,9.33E-2,5.05E15,-12200.,1.79E14,-8830.,TEMP))
  RCONST(537) = (ISO1(1.0E-11,390.,2.26E-1,2.22E9,-7160.,1.75E14,-9054.,TEMP))
  RCONST(538) = (ISO2(1.7E-11,390.,9.33E-2,5.05E15,-12200.,1.79E14,-8830.,TEMP))
  RCONST(539) = (ISO2(1.0E-11,390.,2.26E-1,2.22E9,-7160.,1.75E14,-9054.,TEMP))
  RCONST(540) = ((1.1644-TEMP*7.0485E-4)*6.92E-14)*mol2ppm ! convert to ppm-1 s-1
  RCONST(541) = ((1.2038-TEMP*9.0435E-4)*5.74E-12)*mol2ppm
  RCONST(542) = ((2.3682-TEMP*1.6092E-3)/2*3.08E-12)*mol2ppm
  RCONST(543) = ((TEMP*7.0485E-4-0.1644)*2.49E-12)*mol2ppm
  RCONST(544) = ((TEMP*9.0435E-4-0.2038)*3.94E-12)*mol2ppm
  RCONST(545) = ((TEMP*1.6092E-3-0.3682)/2*3.08E-12)*mol2ppm
  RCONST(546) = (NIT(2.7E-12,350.,1.19,6.,1.1644,7.05E-4,TEMP))
  RCONST(547) = (ALK(2.7E-12,350.,1.19,6.,1.1644,7.05E-4,TEMP))
  RCONST(548) = (NIT(2.7E-12,350.,1.421,6.,-0.1644,-7.05E-4,TEMP))
  RCONST(549) = (ALK(2.7E-12,350.,1.421,6.,-0.1644,-7.05E-4,TEMP))
  RCONST(550) = (NIT(2.7E-12,350.,1.297,6.,1.2038,9.04E-4,TEMP))
  RCONST(551) = (ALK(2.7E-12,350.,1.297,6.,1.2038,9.04E-4,TEMP))
  RCONST(552) = (NIT(2.7E-12,350.,1.421,6.,-0.2038,-9.04E-4,TEMP))
  RCONST(553) = (ALK(2.7E-12,350.,1.421,6.,-0.2038,-9.04E-4,TEMP))
  RCONST(554) = ((1.1644-TEMP*7.0485E-4)*2.12E-13*EXP(1300./TEMP))*mol2ppm
  RCONST(555) = ((TEMP*7.0485E-4-0.1644)*2.12E-13*EXP(1300./TEMP))*mol2ppm
  RCONST(556) = ((1.2038-TEMP*9.0435E-4)*2.12E-13*EXP(1300./TEMP))*mol2ppm
  RCONST(557) = ((TEMP*9.0435E-4-0.2038)*2.12E-13*EXP(1300./TEMP))*mol2ppm
  RCONST(558) = ((1.1644-TEMP*7.0485E-4)*2.00E-12)*mol2ppm
  RCONST(559) = ((TEMP*7.0485E-4-0.1644)*2.00E-12)*mol2ppm
  RCONST(560) = ((1.2038-TEMP*9.0435E-4)*2.00E-12)*mol2ppm
  RCONST(561) = ((TEMP*9.0435E-4-0.2038)*2.00E-12)*mol2ppm
  RCONST(562) = ((1.1644-TEMP*7.0485E-4)*1.04E11*EXP(-9746./TEMP)) !unimolecular reaction
  RCONST(563) = ((TEMP*5.1242E-5-0.0128)*5.05E15*EXP(-12200./TEMP)*EXP(1.E8/TEMP**3))
  RCONST(564) = ((1.2038-TEMP*9.0435E-4)*1.88E11*EXP(-9752./TEMP))
  RCONST(565) = ((TEMP*1.1346E-4-0.0306)*2.22E9*EXP(-7160./TEMP)*EXP(1.E8/TEMP**3))
  RCONST(566) = (2.2E-11*EXP(390./TEMP))*mol2ppm
  RCONST(567) = j(Pj_1co2ooh)
  RCONST(568) = (3.5E-11*EXP(390./TEMP))*mol2ppm
  RCONST(569) = j(Pj_3ooh4co)
  RCONST(570) = (4.64E-12*EXP(650./TEMP))*mol2ppm
  RCONST(571) = (4.64E-12*EXP(650./TEMP))*mol2ppm
  RCONST(572) = (4.35E-12*EXP(390./TEMP))*mol2ppm
  RCONST(573) = (EPO(2.85E-11,390.,4.77E-21,TEMP))
  RCONST(574) = (4.1E-12*EXP(200./TEMP))*mol2ppm
  RCONST(575) = j(Pj_3ooh4oh)
  RCONST(576) = (6.1E-12*EXP(200./TEMP))*mol2ppm
  RCONST(577) = (2.47E-12*EXP(390./TEMP))*mol2ppm
  RCONST(578) = (EPO(1.62E-11,390.,4.77E-21,TEMP))
  RCONST(579) = j(Pj_1oh2ooh)
  RCONST(580) = (2.7E-11*EXP(390./TEMP))*mol2ppm
  RCONST(581) = (2.38E-13*EXP(1300./TEMP))*mol2ppm
  RCONST(582) = (NIT(2.7E-12,350.,13.098,8.,1.,0.,TEMP))
  RCONST(583) = (ALK(2.7E-12,350.,13.098,8.,1.,0.,TEMP))
  RCONST(584) = (1.875E13*EXP(-10000./TEMP))
  RCONST(585) = (3.53E-11*EXP(390./TEMP))*mol2ppm
  RCONST(586) = (3.53E-11*EXP(390./TEMP))*mol2ppm
  RCONST(587) = (TUN(6.80E12,1.12E4,8.46E7,TEMP))
  RCONST(588) = (ALK(2.7E-12,350.,2.1,9.,1.,0.,TEMP))
  RCONST(589) = (NIT(2.7E-12,350.,2.1,9.,1.,0.,TEMP))
  RCONST(590) = (2.47E-13*EXP(1300./TEMP))*mol2ppm
  RCONST(591) = (TUN(3.73E12,1.88E4,1.82E8,TEMP))
  RCONST(592) = (ALK(2.7E-12,350.,2.315,9.,1.,0.,TEMP))
  RCONST(593) = (NIT(2.7E-12,350.,2.315,9.,1.,0.,TEMP))
  RCONST(594) = (2.47E-13*EXP(1300./TEMP))*mol2ppm
  RCONST(595) = (TUN(1.87E12,9.63E3,8.02E7,TEMP))
  RCONST(596) = (ALK(2.7E-12,350.,3.079,9.,1.,0.,TEMP))
  RCONST(597) = (NIT(2.7E-12,350.,3.079,9.,1.,0.,TEMP))
  RCONST(598) = (2.47E-13*EXP(1300./TEMP))*mol2ppm
  RCONST(599) = (3.22E-11*EXP(-400./TEMP))*mol2ppm
  RCONST(600) = (1.05E-11*EXP(-400./TEMP))*mol2ppm
  RCONST(601) = (EPO(5.82E-11,-400.,1.14E-20,TEMP))
  RCONST(602) = (8.25E-12*EXP(-400./TEMP))*mol2ppm
  RCONST(603) = (EPO(3.75E-11,-400.,8.91E-21,TEMP))
  RCONST(604) = (1.875E13*EXP(-10000./TEMP))
  RCONST(605) = (1.0E7*EXP(-5000./TEMP))
  RCONST(606) = (ALK(2.7E-12,350.,16.463,8.,1.,0.,TEMP))
  RCONST(607) = (NIT(2.7E-12,350.,16.463,8.,1.,0.,TEMP))
  RCONST(608) = (2.38E-13*EXP(1300./TEMP))*mol2ppm
  RCONST(609) = (1.875E13*EXP(-10000./TEMP))
  RCONST(610) = (1.0E7*EXP(-5000./TEMP))
  RCONST(611) = (2.38E-13*EXP(1300./TEMP))*mol2ppm
  RCONST(612) = (ALK(2.7E-12,350.,13.098,8.,1.,0.,TEMP))
  RCONST(613) = (NIT(2.7E-12,350.,13.098,8.,1.,0.,TEMP))
  RCONST(614) = (8.7E-12*EXP(70./TEMP))*mol2ppm
  RCONST(615) = (5E-12*EXP(470./TEMP))*mol2ppm
  RCONST(616) = j(Pj_MVK3OH4CO)
  RCONST(617) = (2.0E-12*EXP(70./TEMP))*mol2ppm
  RCONST(618) = j(PJ_MVK3CO4OH)
  RCONST(619) = (2.4E-11*EXP(70./TEMP))*mol2ppm
  RCONST(620) = (5.0E-12*EXP(470./TEMP))*mol2ppm
  RCONST(621) = (2.6E-12*EXP(610./TEMP))*mol2ppm
  RCONST(622) = (2.12E-13*EXP(1300./TEMP))*mol2ppm
  RCONST(623) = (ALK(2.7E-12,350.,4.573,6.,1.,0.,TEMP))
  RCONST(624) = (NIT(2.7E-12,350.,4.573,6.,1.,0.,TEMP))
  RCONST(625) = (4.4E-12*EXP(380./TEMP))*mol2ppm
  RCONST(626) = (2.7E-12*EXP(470./TEMP))*mol2ppm
  RCONST(627) = (2.12E-13*EXP(1300./TEMP))*mol2ppm
  RCONST(628) = (3.14E-12*EXP(580./TEMP))*mol2ppm
  RCONST(629) = (2.9E7*EXP(-5297./TEMP))
  RCONST(630) = (ALK(2.7E-12,350.,2.985,6.,1.,0.,TEMP))
  RCONST(631) = (NIT(2.7E-12,350.,2.985,6.,1.,0.,TEMP))
  RCONST(632) = (8.7E-12*EXP(290./TEMP))*mol2ppm
  RCONST(633) = (TROEPOW(2.591E-28,0.,-6.87,1.125E-11,0.,-1.105,0.3,TEMP))
  RCONST(634) = (1.58E16*EXP(-13500./TEMP))
 RCONST(635) = 2.9E-11*mol2ppm !constant rate coefficient
  RCONST(636) = j(PJ_1CO4OOH)
  RCONST(637) = j(Pj_1OOH4CO)
  RCONST(638) = (1.17E-11*EXP(450./TEMP))*mol2ppm
  RCONST(639) = (1.17E-11*EXP(450./TEMP))*mol2ppm
  RCONST(640) = (2.7E-12*EXP(350./TEMP))*mol2ppm
  RCONST(641) = (1.93E-13*EXP(1300./TEMP))*mol2ppm
 RCONST(642) = 9.0E-12*mol2ppm!constant rate coefficient
  RCONST(643) = (2.7E-12*EXP(350./TEMP))*mol2ppm
  RCONST(644) = (1.93E-13*EXP(1300./TEMP))*mol2ppm
 RCONST(645) = 9.0E-12*mol2ppm!constant rate coefficient
  RCONST(646) = j(Pj_MCRENOL)
  RCONST(647) = j(Pj_MVKENOL)
  RCONST(648) = (3.83E-12*EXP(983./TEMP))*mol2ppm
  RCONST(649) = (3.35E-12*EXP(983./TEMP))*mol2ppm
  RCONST(650) = (5.0E-12*EXP(470./TEMP))*mol2ppm
  RCONST(651) = j(Pj_MVK3OOH4CO)
  RCONST(652) = (2.7E-12*EXP(350./TEMP))*mol2ppm
  RCONST(653) = (2.38E-12*EXP(1300./TEMP))*mol2ppm
  RCONST(654) = (2.7E-12*EXP(350./TEMP))*mol2ppm
  RCONST(655) = (2.38E-12*EXP(1300./TEMP))*mol2ppm
  RCONST(656) = (7.14E-12*EXP(390./TEMP))*mol2ppm
  RCONST(657) = (EPO(6.30E-12,390.,1.62E-19,TEMP))
  RCONST(658) = (1.02E-11*EXP(390./TEMP))*mol2ppm
  RCONST(659) = (EPO(1.05E-11,390.,2.49E-19,TEMP))
  RCONST(660) = (1.875E13*EXP(-10000./TEMP))
  RCONST(661) = (2.6E-13*EXP(1300./TEMP))*mol2ppm
  RCONST(662) = (ALK(2.7E-12,350.,6.32,11.,1.,0.,TEMP))
  RCONST(663) = (NIT(2.7E-12,350.,6.32,11.,1.,0.,TEMP))
  RCONST(664) = (1.875E13*EXP(-10000./TEMP))
  RCONST(665) = (2.6E-13*EXP(1300./TEMP))*mol2ppm
  RCONST(666) = (ALK(2.7E-12,350.,7.941,11.,1.,0.,TEMP))
  RCONST(667) = (NIT(2.7E-12,350.,7.941,11.,1.,0.,TEMP))
 RCONST(668) = 1.3E-17*mol2ppm!constant rate coefficient
 RCONST(669) = 1.7E-15*mol2ppm!constant rate coefficient
  RCONST(670) = (2.88E-35*EXP(1391./TEMP))*mol2ppm*mol2ppm !trimolecular reaction
  RCONST(671) = (2.0E-12*0.7)*mol2ppm
  RCONST(672) = (1.3E-12*EXP(500./TEMP))*mol2ppm
  RCONST(673) = (2.95E-12*EXP(-450./TEMP))*mol2ppm
  RCONST(674) = (2.47E-13*EXP(1300./TEMP))*mol2ppm
  RCONST(675) = (2.47E-13*EXP(1300./TEMP))*mol2ppm
 RCONST(676) =2.56E-12*mol2ppm! constant rate coefficient
 RCONST(677) =3.71E-12*mol2ppm! constant rate coefficient
 RCONST(678) = 1.61E-12*mol2ppm! constant rate coefficient
 RCONST(679) = 2.80E-12*mol2ppm! constant rate coefficient
 RCONST(680) = 1.18E-12*mol2ppm! constant rate coefficient
 RCONST(681) = 1.92E-12*mol2ppm! constant rate coefficient
 RCONST(682) = 7.71E-12*mol2ppm! constant rate coefficient
 RCONST(683) = 2.3E-12*mol2ppm! constant rate coefficient
 RCONST(684) = 2.3E-12*mol2ppm! constant rate coefficient
  RCONST(685) = (ALK(2.7E-12,350.,12.915,9.,1.,0.,TEMP))
  RCONST(686) = (NIT(2.7E-12,350.,12.915,9.,1.,0.,TEMP))
  RCONST(687) = (ALK(2.7E-12,350.,1.412,9.,1.,0.,TEMP))
  RCONST(688) = (NIT(2.7E-12,350.,1.412,9.,1.,0.,TEMP))
  RCONST(689) = (2.5E-14*EXP(-300./TEMP))*mol2ppm
  RCONST(690) = (1.0E20*EXP(-10000./TEMP))
  RCONST(691) = (8.72E-12*EXP(390./TEMP))*mol2ppm
  RCONST(692) = (EPO(1.55E-11,390.,2.715E-19,TEMP))
  RCONST(693) = (2.04E-11*EXP(390./TEMP))*mol2ppm
  RCONST(694) = (7.5E-12*EXP(20./TEMP))*mol2ppm
  RCONST(695) = (EPO(9.52E-12,390.,2.715E-19,TEMP))
  RCONST(696) = (2.95E-11*EXP(390./TEMP))*mol2ppm
  RCONST(697) = (7.5E-12*EXP(20./TEMP))*mol2ppm
  RCONST(698) = (2.6E-13*EXP(1300./TEMP))*mol2ppm
  RCONST(699) = (ALK(2.7E-12,350.,4.712,11.,1.,0.,TEMP))
  RCONST(700) = (NIT(2.7E-12,350.,4.712,11.,1.,0.,TEMP))
  RCONST(701) = (1.256E13*EXP(-10000./TEMP))
  RCONST(702) = (2.6E-13*EXP(1300./TEMP))*mol2ppm
  RCONST(703) = (ALK(2.7E-12,350.,2.258,11.,1.,0.,TEMP))
  RCONST(704) = (NIT(2.7E-12,350.,2.258,11.,1.,0.,TEMP))
  RCONST(705) = (5.092E12*EXP(-10000./TEMP))
  RCONST(706) = (2.6E-13*EXP(1300./TEMP))*mol2ppm
  RCONST(707) = (ALK(2.7E-12,350.,1.851,11.,1.,0.,TEMP))
  RCONST(708) = (NIT(2.7E-12,350.,1.851,11.,1.,0.,TEMP))
  RCONST(709) = (0.5102*8.72E-12*EXP(390./TEMP))*mol2ppm
  RCONST(710) = (0.6778*2.37E-11*EXP(390./TEMP))*mol2ppm
  RCONST(711) = (EPO(6.673E-12,390.,2.28E-20,TEMP))
  RCONST(712) = (EPO(8.77E-12,390.,2.185E-20,TEMP))
  RCONST(713) = (EPO(1.493E-11,390.,2.715E-19,TEMP))
  RCONST(714) = (3.4E-12*EXP(200./TEMP))*mol2ppm
  RCONST(715) = (3.4E-12*EXP(200./TEMP))*mol2ppm
  RCONST(716) = (7.5E-12*EXP(20./TEMP))*mol2ppm
  RCONST(717) = (6.55E12*EXP(-10000./TEMP))
  RCONST(718) = (8.72E12*EXP(-10000./TEMP))
  RCONST(719) = (2.64E-13*EXP(1300./TEMP))*mol2ppm
  RCONST(720) = (2.64E-13*EXP(1300./TEMP))*mol2ppm
  RCONST(721) = (ALK(2.7E-12,350.,6.092,12.,1.,0.,TEMP))
  RCONST(722) = (NIT(2.7E-12,350.,6.092,12.,1.,0.,TEMP))
  RCONST(723) = (ALK(2.7E-12,350.,4.383,12.,1.,0.,TEMP))
  RCONST(724) = (NIT(2.7E-12,350.,4.383,12.,1.,0.,TEMP))
  RCONST(725) = (EPO(3.22E-11,-400.,1.014E-20,TEMP))
  RCONST(726) = (7.77E-12*EXP(-400./TEMP))*mol2ppm
  RCONST(727) = (2.6E-13*EXP(1300./TEMP))*mol2ppm
  RCONST(728) = (NIT(2.7E-12,350.,15.73,11.,1.,0.,TEMP))
  RCONST(729) = (ALK(2.7E-12,350.,15.73,11.,1.,0.,TEMP))
  RCONST(730) = (EPO(3.35E-12,390.,2.715E-19,TEMP))
  RCONST(731) = (4.42E-12*EXP(390./TEMP))*mol2ppm
  RCONST(732) = (6.48E-12*EXP(390./TEMP))*mol2ppm
  RCONST(733) = (EPO(2.09E-12,390.,2.715E-19,TEMP))
  RCONST(734) = (2.7E-12*EXP(390./TEMP))*mol2ppm
  RCONST(735) = (1.0E7*EXP(-5000./TEMP))
  RCONST(736) = (2.6E-13*EXP(1300./TEMP))*mol2ppm
  RCONST(737) = (ALK(2.7E-12,350.,22.837,11.,1.,0.,TEMP))
  RCONST(738) = (NIT(2.7E-12,350.,22.837,11.,1.,0.,TEMP))
  RCONST(739) = (1E7*EXP(-5000./TEMP))
  RCONST(740) = (2.6E-13*EXP(1300./TEMP))*mol2ppm
  RCONST(741) = (ALK(2.7E-12,350.,18.181,11.,1.,0.,TEMP))
  RCONST(742) = (NIT(2.7E-12,350.,18.181,11.,1.,0.,TEMP))
  RCONST(743) = (2.6E-13*EXP(1300./TEMP))*mol2ppm
  RCONST(744) = (NIT(2.7E-12,350.,18.181,11.,1.,0.,TEMP))
  RCONST(745) = (ALK(2.7E-12,350.,18.181,11.,1.,0.,TEMP))
  RCONST(746) = j(Pj_1N4CO)
  RCONST(747) = j(Pj_1CO4N)
  RCONST(748) = j(Pj_3CO4N)
  RCONST(749) = (3.3E-12*EXP(470./TEMP))*mol2ppm
  RCONST(750) = (3.3E-12*EXP(470./TEMP))*mol2ppm
  RCONST(751) = (2.7E-12*EXP(350./TEMP))*mol2ppm
  RCONST(752) = (2.54E-13*EXP(1300./TEMP))*mol2ppm
  RCONST(753) = (2.7E-12*EXP(350./TEMP))*mol2ppm
  RCONST(754) = (2.54E-13*EXP(1300./TEMP))*mol2ppm
  RCONST(755) = (9.85E-12*EXP(410./TEMP))*mol2ppm
  RCONST(756) = (9.85E-12*EXP(410./TEMP))*mol2ppm
END SUBROUTINE Update_RCONST

! End of Update_RCONST function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_PHOTO - function to update photolytical rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_PHOTO ( )


!   USE cacm3_Global

      
END SUBROUTINE Update_PHOTO

! End of Update_PHOTO function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE cacm3_Rates

