! 
! THIS FILE WAS AUTOMATICALLY GENERATED BY 
!
!      tools/gen_kpp_interface.c   
!
! MANUAL CHANGES TO THIS FILE WILL BE LOST !!! 
! 
! 
MODULE module_interf 


  USE cacm3_Parameters
  USE cacm3_Precision
  USE cacm3_Rates
  USE cacm3_Integrator
  USE module_wkppc_constants
  USE parameters  ! ddw - use the parameter module by user

   implicit none
! ddw - modify when change chemical mechanism
! locally define pointers to photolysis rates
      INTEGER, PARAMETER, PRIVATE ::     Pj_no2  = 1
      INTEGER, PARAMETER, PRIVATE ::     Pj_no3o2  =2
      INTEGER, PARAMETER, PRIVATE ::     Pj_no3o  =3
      INTEGER, PARAMETER, PRIVATE ::     Pj_o33p  =4
      INTEGER, PARAMETER, PRIVATE ::     Pj_o31d  =5
      INTEGER, PARAMETER, PRIVATE ::     Pj_hno2  =6
      INTEGER, PARAMETER, PRIVATE ::     Pj_h2o2  =7
      INTEGER, PARAMETER, PRIVATE ::     Pj_ooh1  =8
      INTEGER, PARAMETER, PRIVATE ::     Pj_ooh2  =9
      INTEGER, PARAMETER, PRIVATE ::     Pj_rpr2301 =10
      INTEGER, PARAMETER, PRIVATE ::     Pj_ch2or  =11
      INTEGER, PARAMETER, PRIVATE ::     Pj_ch2om  =12
      INTEGER, PARAMETER, PRIVATE ::     Pj_ch3cho  =13
      INTEGER, PARAMETER, PRIVATE ::     Pj_ald2  =14
      INTEGER, PARAMETER, PRIVATE ::     Pj_ch3coc2h5  =15
      INTEGER, PARAMETER, PRIVATE ::     Pj_ooh6101  =16
      INTEGER, PARAMETER, PRIVATE ::     Pj_ooh6102  =17
      INTEGER, PARAMETER, PRIVATE ::     Pj_hac  =18
      INTEGER, PARAMETER, PRIVATE ::     Pj_ap6101  =19
      INTEGER, PARAMETER, PRIVATE ::     Pj_ap6102  =20
      INTEGER, PARAMETER, PRIVATE ::     Pj_nald  =21
      INTEGER, PARAMETER, PRIVATE ::     Pj_hpald  =22
      INTEGER, PARAMETER, PRIVATE ::     Pj_pacald  =23
      INTEGER, PARAMETER, PRIVATE ::     Pj_macr  =24
      INTEGER, PARAMETER, PRIVATE ::     Pj_rp6301  =25
      INTEGER, PARAMETER, PRIVATE ::     Pj_ooh6301  =26
      INTEGER, PARAMETER, PRIVATE ::     Pj_hcochob  =27
      INTEGER, PARAMETER, PRIVATE ::     Pj_rp7102  =28
      INTEGER, PARAMETER, PRIVATE ::     Pj_ch3cocho  =29
      INTEGER, PARAMETER, PRIVATE ::     Pj_pina  =30
      INTEGER, PARAMETER, PRIVATE ::     Pj_nrpa  =31
      INTEGER, PARAMETER, PRIVATE ::     Pj_edlm  =32
      INTEGER, PARAMETER, PRIVATE ::     Pj_lmkt  =33
      INTEGER, PARAMETER, PRIVATE ::     Pj_rpr8401  =34
      INTEGER, PARAMETER, PRIVATE ::     Pj_rpr8501  =35
      INTEGER, PARAMETER, PRIVATE ::     Pj_ooh8601  =36
      INTEGER, PARAMETER, PRIVATE ::     Pj_ooh8602  =37
      INTEGER, PARAMETER, PRIVATE ::     Pj_1co2ooh  =38
      INTEGER, PARAMETER, PRIVATE ::     Pj_3ooh4co  =39
      INTEGER, PARAMETER, PRIVATE ::     Pj_3ooh4oh  =40
      INTEGER, PARAMETER, PRIVATE ::     Pj_1oh2ooh  =41
      INTEGER, PARAMETER, PRIVATE ::     Pj_mvk3oh4co  =42
      INTEGER, PARAMETER, PRIVATE ::     Pj_mvk3co4oh  =43
      INTEGER, PARAMETER, PRIVATE ::     Pj_1co4ooh  =44
      INTEGER, PARAMETER, PRIVATE ::     Pj_1ooh4co  =45
      INTEGER, PARAMETER, PRIVATE ::     Pj_mcrenol  =46
      INTEGER, PARAMETER, PRIVATE ::     Pj_mvkenol  =47
      INTEGER, PARAMETER, PRIVATE ::     Pj_mvk3ooh4co  =48
      INTEGER, PARAMETER, PRIVATE ::     Pj_1n4co  =49
      INTEGER, PARAMETER, PRIVATE ::     Pj_1co4n  =50
      INTEGER, PARAMETER, PRIVATE ::     Pj_3co4n  =51

CONTAINS 

!ddw -  change the inputs accordingly 
SUBROUTINE  cacm_interface(timloc, &
             nspec, vc,  dtstepc, &        ! parameters
             p_phy,t_phy,rho_phy,moist,  & ! ddw -  meteo
             ph_o31d, ph_o33p, ph_no2, ph_no3o2, ph_no3o, & 
             ph_hno2, ph_hno3, ph_hno4, ph_h2o2, ph_ch2or, & 
             ph_ch2om, ph_ch3cho, ph_ch3coch3, ph_ch3coc2h5, ph_hcocho, & 
             ph_ch3cocho, ph_hcochest, ph_ch3o2h, ph_ch3coo2h, ph_ch3ono2, & 
             ph_hcochob, ph_macr, ph_hobr, ph_br2, ph_bro, & 
             ph_n2o5, ph_o2, ph_pan, ph_acet, ph_mglo, & 
             ph_hno4_2, ph_c6h5cho, ph_unald, ph_n2o, ph_pooh, & 
             ph_mpan, ph_mvk, ph_etooh, ph_prooh, ph_onitr, & 
             ph_acetol, ph_glyald, ph_hyac, ph_mek, ph_open, & 
             ph_gly, ph_acetp, ph_xooh, ph_isooh, ph_alkooh, & 
             ph_mekooh, ph_tolooh, ph_terpooh,  & 
             ph_ooh1, ph_ooh2, ph_rpr2301, ph_ald2, ph_ooh6101, &   ! new photolysis
             ph_ooh6102, ph_hac, ph_ap6101, ph_ap6102, ph_nald, &
             ph_hpald, ph_pacald, ph_rp6301, ph_ooh6301, ph_rp7102, &
             ph_pina, ph_nrpa, ph_edlm, ph_lmkt, ph_rpr8401, &
             ph_rpr8501, ph_ooh8601, ph_ooh8602, & 
             ph_1co2ooh, ph_3ooh4co,  ph_3ooh4oh, ph_1oh2ooh, ph_mvk3oh4co, & !POW photolysis 
             ph_mvk3co4oh, ph_1co4ooh, ph_1ooh4co, ph_mcrenol, ph_mvkenol,  &
             ph_mvk3ooh4co, ph_1n4co, ph_1co4n, ph_3co4n, &
             RCONST)   ! ddw - reaction rates

    IMPLICIT NONE


    INTEGER,      INTENT(IN   ) ::    nspec
    REAL   ,      INTENT(IN   ) ::    dtstepc, timloc, &
                                      moist, p_phy, t_phy, rho_phy
    REAL,         INTENT(INOUT) ::    vc(nspec) ! in ppb*1.0E-9

! photolysis rates 
    REAL,     INTENT(INOUT ) ::  & ! in s-1 
               ph_o31d, ph_o33p, ph_no2, ph_no3o2, ph_no3o, & 
               ph_hno2, ph_hno3, ph_hno4, ph_h2o2, ph_ch2or, & 
               ph_ch2om, ph_ch3cho, ph_ch3coch3, ph_ch3coc2h5, ph_hcocho, & 
               ph_ch3cocho, ph_hcochest, ph_ch3o2h, ph_ch3coo2h, ph_ch3ono2, & 
               ph_hcochob, ph_macr, ph_hobr, ph_br2, ph_bro, & 
               ph_n2o5, ph_o2, ph_pan, ph_acet, ph_mglo, & 
               ph_hno4_2, ph_c6h5cho, ph_unald, ph_n2o, ph_pooh, & 
               ph_mpan, ph_mvk, ph_etooh, ph_prooh, ph_onitr, & 
               ph_acetol, ph_glyald, ph_hyac, ph_mek, ph_open, & 
               ph_gly, ph_acetp, ph_xooh, ph_isooh, ph_alkooh, & 
               ph_mekooh, ph_tolooh, ph_terpooh, & 
               ph_ooh1, ph_ooh2, ph_rpr2301, ph_ald2, ph_ooh6101, &   ! new photolysis
               ph_ooh6102, ph_hac, ph_ap6101, ph_ap6102, ph_nald, &
               ph_hpald, ph_pacald, ph_rp6301, ph_ooh6301, ph_rp7102, &
               ph_pina, ph_nrpa, ph_edlm, ph_lmkt, ph_rpr8401, &
               ph_rpr8501, ph_ooh8601, ph_ooh8602, & 
               ph_1co2ooh, ph_3ooh4co,  ph_3ooh4oh, ph_1oh2ooh, ph_mvk3oh4co, & 
               ph_mvk3co4oh, ph_1co4ooh, ph_1ooh4co, ph_mcrenol, ph_mvkenol,  &
               ph_mvk3ooh4co, ph_1n4co, ph_1co4n, ph_3co4n


! local variables 

    INTEGER, PARAMETER :: njv=53
    REAL(KIND=dp), DIMENSION(njv) :: jv


    REAL(KIND=dp):: TIME_START
    REAL(KIND=dp):: TIME_END

    INTEGER, DIMENSION(20) :: ICNTRL 
    REAL(KIND=dp), DIMENSION(20) :: RCNTRL
    INTEGER, DIMENSION(20) :: ISTATUS 
    REAL(KIND=dp), DIMENSION(20) :: RSTATUS
    INTEGER :: IERR_U

    REAL(KIND=dp), DIMENSION(NREACT):: RCONST 

    REAL(KIND=dp), DIMENSION(NVAR) :: var
    REAL(KIND=dp), DIMENSION(NFIX) :: fix

     !temperature (K)
    REAL(KIND=dp)   :: TEMP 

    REAL(KIND=dp), DIMENSION(NSPEC) :: ATOL, RTOL

    REAL(KIND=dp) :: conv, oconv 
    REAL(KIND=dp) :: C_M 

    INTEGER :: i,j,k,n 
    
! SETTINGS FOR ICNTRL, RCNTRL IN in chem/KPP/inc/kpp_ctrl_default.inc 
      DO n=1, 20
         ICNTRL(n) = 0
         RCNTRL(n) = 0._dp
      END DO

! CURRENTLY FROM in chem/KPP/module_wkppc_constants.F 
      DO n=1, NSPEC
         ATOL(n) = REAL(atols, KIND=dp)
         RTOL(n) = REAL(rtols, KIND=dp)
      END DO


      TIME_START = 0.0_dp 
      TIME_END =  REAL(dtstepc, KIND=dp) 

      ! 3rd body concentration (molec/cm^3)
      ! ddw - change 3D rho_phy to 1D array
      ! ddw -  indf_O2 = 2 (Parameters.F)
!    FIX(indf_O2)  = REAL(dens2con_a * rho_phy, KIND=dp)
    FIX(indf_O2)  = 0.21E6_dp 
    C_M = FIX(indf_O2)
      
      ! water concentration (molec/cm^3)
      ! ddw - change 3D rho_phy and moist to 1D array
      ! ddw - indf_H2O = 1 (Parameters.F)
!    FIX(indf_H2O) = REAL(dens2con_w * moist * rho_phy, KIND=dp)
     FIX(indf_H2O) = real(vc(lh2o)*1.0E6, KIND=dp)  ! in ppmv 

      ! FIX(1) was for Photolysis rate in old CACM
      FIX(indf_UV) = 1.0_dp  ! it is handled in main in this version
      FIX(indf_DUMMY) = 1.0_dp  ! EMS 
      ! temperature (K)
      ! ddw - change 3D t_phy to 1D array
    TEMP = REAL(t_phy, KIND=dp)

     ! convesion from ppmV to molecules/cm3 and back
     ! ddw - change 3D rho_phy to 1D array
     !     conv=1.E-6_dp*dens2con_a*rho_phy
!     conv=dens2con_a*rho_phy
!     oconv = 1.E0_dp/conv

! 3D to 1D for ph_*
! photolysis reactions in cacm
    jv(Pj_no2) = REAL(ph_no2   , KIND=dp)   !R1 
    jv(Pj_no3o2) = REAL(ph_no3o2  , KIND=dp)!R13 
    jv(Pj_no3o) = REAL(ph_no3o  , KIND=dp)  !R14 
    jv(Pj_o33p) = REAL(ph_o33p , KIND=dp)   !R15 
    jv(Pj_o31d) = REAL(ph_o31d , KIND=dp)   !R16 
    jv(Pj_hno2) = REAL(ph_hno2  , KIND=dp)  !R20 
    jv(Pj_h2o2) = REAL(ph_h2o2  , KIND=dp)  !R36 
    jv(Pj_ooh1) = REAL(ph_ooh1  , KIND=dp)  !R43 
    jv(Pj_ooh2) = REAL(ph_ooh2  , KIND=dp)  !R46 
    jv(Pj_rpr2301) = REAL(ph_rpr2301  , KIND=dp)  !R119 
    jv(Pj_ch2or) = REAL(ph_ch2or  , KIND=dp)!R125 
    jv(Pj_ch2om) = REAL(ph_ch2om  , KIND=dp)!R126 
    jv(Pj_ch3cho) = REAL(ph_ch3cho  , KIND=dp)!R129(ald) 
    jv(Pj_ald2) = REAL(ph_ald2  , KIND=dp)!R137 
    jv(Pj_ch3coc2h5) = REAL(ph_ch3coc2h5  , KIND=dp)!R150(ketl)&R155(keth) 
    jv(Pj_ooh6101) = REAL(ph_ooh6101 , KIND=dp)  !R193 
    jv(Pj_ooh6102) = REAL(ph_ooh6102 , KIND=dp)  !R194 
    jv(Pj_hac) = REAL(ph_hac , KIND=dp)  !R211 
    jv(Pj_ap6101) = REAL(ph_ap6101 , KIND=dp) !R216 
    jv(Pj_ap6102) = REAL(ph_ap6102 , KIND=dp) !R219 
    jv(Pj_nald) = REAL(ph_nald , KIND=dp) !R220 
    jv(Pj_hpald) = REAL(ph_hpald, KIND=dp) !R222 
    jv(Pj_pacald) = REAL(ph_pacald, KIND=dp) !R224 
    jv(Pj_macr) = REAL(ph_macr  , KIND=dp)!R237 
    jv(Pj_rp6301) = REAL(ph_rp6301 , KIND=dp)!R259 
    jv(Pj_ooh6301) = REAL(ph_ooh6301, KIND=dp) !R265 
    jv(Pj_hcochob) = REAL(ph_hcochob  , KIND=dp)!R269(glyx-->2co+2HO2) 
    jv(Pj_rp7102) = REAL(ph_rp7102, KIND=dp)!R288 
    jv(Pj_ch3cocho) = REAL(ph_ch3cocho  , KIND=dp) !R291 
    jv(Pj_pina) = REAL(ph_pina, KIND=dp) !R412 
    jv(Pj_nrpa) = REAL(ph_nrpa, KIND=dp) !R420 
    jv(Pj_edlm) = REAL(ph_edlm, KIND=dp) !R496 
    jv(Pj_lmkt) = REAL(ph_lmkt, KIND=dp) !R506 
    jv(Pj_rpr8401) = REAL(ph_rpr8401, KIND=dp) !R563 
    jv(Pj_rpr8501) = REAL(ph_rpr8501, KIND=dp) !R593&R594 
    jv(Pj_ooh8601) = REAL(ph_ooh8601, KIND=dp) !R616 
    jv(Pj_ooh8602) = REAL(ph_ooh8602, KIND=dp) !R617 
    jv(Pj_1co2ooh) = REAL(ph_1co2ooh, KIND=dp) !ISOP1CO2OOH (POW-ISOP mechanism) 
    jv(Pj_3ooh4co) = REAL(ph_3ooh4co, KIND=dp) !ISOP3OOH4CO (POW-ISOP mechanism) 
    jv(Pj_3ooh4oh) = REAL(ph_3ooh4oh, KIND=dp) !ISOP3OOH4OH (POW-ISOP mechanism) 
    jv(Pj_1oh2ooh) = REAL(ph_1oh2ooh, KIND=dp) !ISO1OH2OOHH (POW-ISOP mechanism) 
    jv(Pj_mvk3oh4co) = REAL(ph_mvk3oh4co, KIND=dp) !MVK3OH4CO (POW-ISOP mechanism) 
    jv(Pj_mvk3co4oh) = REAL(ph_mvk3co4oh, KIND=dp) !MVK3CO4OH (POW-ISOP mechanism) 
    jv(Pj_1co4ooh) = REAL(ph_1co4ooh, KIND=dp) !ISOP1CO4OOH (POW-ISOP mechanism) 
    jv(Pj_1ooh4co) = REAL(ph_1ooh4co, KIND=dp) !ISOP1OOH4CO (POW-ISOP mechanism) 
    jv(Pj_mcrenol) = REAL(ph_mcrenol, KIND=dp) !MCRENOL (POW-ISOP mechanism) 
    jv(Pj_mvkenol) = REAL(ph_mvkenol, KIND=dp) !MVKENOL (POW-ISOP mechanism) 
    jv(Pj_mvk3ooh4co) = REAL(ph_mvk3ooh4co, KIND=dp) !MVK3OOH4CO (POW-ISOP mechanism) 
    jv(Pj_1n4co) = REAL(ph_1n4co, KIND=dp) !ISOP1N4CO (POW-ISOP mechanism) 
    jv(Pj_1co4n) = REAL(ph_1co4n, KIND=dp) !ISOP1CO4N (POW-ISOP mechanism) 
    jv(Pj_3co4n) = REAL(ph_3co4n, KIND=dp) !ISOP3CO4N (POW-ISOP mechanism) 

! ddw - 3D to 1D
! pass Forcast variables to KPP variables
! ddw - ind_* are the index in KPP generated files (Parameters.F)
! ddw - l*    are the index in FORCAST (parameters_ddw.f90)
! the index in FCAST and in KPP are the same
! therefore a loop can be used here
! But note that NSPEC and NVAR have different sizes

     ! CACHE: vc in ppbV*1E-9; KPP: var in molecs/cm3
     ! CACHE: vc in ppbV*1E-9; CACM: var in ppmv
     ! vc*1E6 --> ppmv
     ! vc*1E6 * 1E-6 * dens2con_a * rho_phy -> molecs/cm3
     conv = 1.0E6_dp 
     oconv = 1.E0_dp/conv

     do i = 1, NVAR
       var(i) = conv * REAL( MAX(vc(i),0.), KIND=dp)  
     end do
! an example var(ind_O3) = conv  * REAL( MAX(vc(lo3),0.), KIND=dp)  
   CALL Update_Rconst(  &
                      jv, njv,  &
                      RCONST ,  &
                      var, &
                      Pj_no2 , Pj_no3o2 , Pj_no3o , Pj_o33p , Pj_o31d , &
                      Pj_hno2 , Pj_h2o2 , Pj_ooh1 , Pj_ooh2 , Pj_rpr2301, &
                      Pj_ch2or , Pj_ch2om , Pj_ch3cho , Pj_ald2 , Pj_ch3coc2h5 , &
                      Pj_ooh6101 , Pj_ooh6102 , Pj_hac , Pj_ap6101 , Pj_ap6102 , &
                      Pj_nald , Pj_hpald , Pj_pacald , Pj_macr , Pj_rp6301 , &
                      Pj_ooh6301 , Pj_hcochob , Pj_rp7102 , Pj_ch3cocho , Pj_pina , &
                      Pj_nrpa , Pj_edlm , Pj_lmkt , Pj_rpr8401 , Pj_rpr8501 , &
                      Pj_ooh8601 , Pj_ooh8602 , &
                      Pj_1co2ooh, pj_3ooh4co,  pj_3ooh4oh, pj_1oh2ooh, pj_mvk3oh4co, & !POW photolysis 
             pj_mvk3co4oh, pj_1co4ooh, pj_1ooh4co, pj_mcrenol, pj_mvkenol,  &
             pj_mvk3ooh4co, pj_1n4co, pj_1co4n, pj_3co4n, &
                      C_M, FIX(indf_H2O), TEMP)

  CALL INTEGRATE(TIME_START, TIME_END, &  
          FIX, VAR,  RCONST, ATOL, RTOL, & 
          ICNTRL_U=icntrl, RCNTRL_U=rcntrl  )
!#include <kpp_mechd_ia_racm_mim.inc> 
! ddw - pass var back to vc 
! ddw - change 3D to 1D 
! the index in FCAST and in KPP are the same
! therefore a loop can be used here
! Note that NSPEC and NVAR have different sizes

    do i=1, NVAR
       vc(i) = MAX ( REAL (oconv * var(i), KIND=sp), 0.)  
    enddo
! an example    vc(lo3) = MAX ( REAL (oconv * var(ind_O3), KIND=sp), 0.)  
END SUBROUTINE  cacm_interface


END MODULE module_interf 



